// stageData.cpp
#include "stageData.h"

std::vector<StageInfo> stageData = {
    // stageId, description, bgmFileName, patternFunc
    { "sample", "AIに渡すためのサンプル。使える素材の一覧を教える", "field", EnemyPat_SampleForAI },
    { "handmade1", "3WAY自機狙い", "Torpedo_Hymn2", EnemyPat_3Way },
    { "handmade2", "全方位", "Torpedo_Hymn2", EnemyPat_Round },
    { "handmade3", "破裂弾", "Torpedo_Hymn2", EnemyPat_Burst },
    { "handmade4", "波と粒の境界（目コピ）", "Torpedo_Hymn2", EnemyPat_Namitsubu },
    { "handmade5", "ドーブルをモチーフにした弾幕。くろいまなざし→キノコのほうし→ロックオン→つのドリル", "Torpedo_Hymn2", EnemyPat_Smeargle },
    { "ClaudeEX1", "高難易度の弾幕", "Torpedo_Hymn", EnemyPat_Difficulty_Claude },
    { "ClaudeEX2", "幾何学的に美しい弾幕 アナザー", "Torpedo_Hymn", EnemyPat_Geometry_Claude2 },
    { "GrokEX1", "彗星をモチーフにした弾幕 アナザー", "Torpedo_Hymn", EnemyPat_Comet_Grok2 },
    { "DeepSeekEx1", "はかいこうせんをモチーフにした弾幕 アナザー", "Torpedo_Hymn", EnemyPat_Hakaikousen_DeepSeek2 },
    { "GeminiEx1", "達人王みたいな弾幕", "Torpedo_Hymn", EnemyPat_Tatsujinou_Gemini },
    { "DeepSeekEx2", "はっぱカッターをモチーフにした弾幕 アナザー", "Torpedo_Hymn", EnemyPat_RazorLeaf_DeepSeek2 },
    { "ClaudeEx3", "達人王みたいな弾幕", "Torpedo_Hymn", EnemyPat_Tatsujinou_Claude },
    { "ClaudeEx4", "蜂をモチーフにした弾幕", "Torpedo_Hymn", EnemyPat_Bee_Claude2 },
    { "GeminiEx2", "闇符「ディマーケイション」LUNATIC", "Torpedo_Hymn", EnemyPat_Demarcation_Gemini },
    { "DeepSeek", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_DeepSeek },
    { "ChatGPT", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_ChatGPT },
    { "Gemini", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Gemini },
    { "Grok", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Grok },
    { "Sakana", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Sakana },
    { "Claude", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Claude },
    { "Qwen", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Qwen },
    { "Vibe", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Vibe },
    { "DeepSeek2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_DeepSeek },
    { "ChatGPT2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_ChatGPT },
    { "Gemini2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Gemini },
    { "Grok2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Grok },
    { "Sakana2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Sakana },
    { "Claude2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Claude },
    { "Qwen2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Qwen },
    { "Vibe2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Vibe },
    { "DeepSeek3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_DeepSeek },
    { "ChatGPT3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_ChatGPT },
    { "Gemini3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Gemini },
    { "Grok3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Grok },
    { "Sakana3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Sakana },
    { "Claude3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Claude },
    { "Qwen3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Qwen },
    { "Vibe3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Vibe },
    { "DeepSeek4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_DeepSeek },
    { "ChatGPT4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_ChatGPT },
    { "Gemini4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Gemini },
    { "Grok4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Grok },
    { "Sakana4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Sakana },
    { "Claude4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Claude },
    { "Qwen4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Qwen },
    { "Vibe4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Vibe },
    { "DeepSeek5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_DeepSeek },
    { "ChatGPT5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_ChatGPT },
    { "Gemini5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Gemini },
    { "Grok5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Grok },
    { "Sakana5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Sakana },
    { "Claude5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Claude },
    { "Qwen5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Qwen },
    { "Vibe5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Vibe },
    { "DeepSeek6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_DeepSeek },
    { "ChatGPT6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_ChatGPT },
    { "Gemini6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_Gemini },
    { "Grok6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_Grok },
    { "Sakana6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_Sakana },
    { "Claude6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_Claude },
    { "Qwen6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_Qwen },
    { "Vibe6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namitsubu_Vibe },
    { "DeepSeek7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_DeepSeek },
    { "ChatGPT7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_ChatGPT },
    { "Gemini7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Gemini },
    { "Grok7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Grok },
    { "Sakana7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Sakana },
    { "Claude7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Claude },
    { "Qwen7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Qwen },
    { "Vibe7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Vibe },
    { "DeepSeek8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_DeepSeek },
    { "ChatGPT8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_ChatGPT },
    { "Gemini8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Gemini },
    { "Grok8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Grok },
    { "Sakana8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Sakana },
    { "Claude8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Claude },
    { "Qwen8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Qwen },
    { "Vibe8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Vibe },
    { "DeepSeek9", "吹雪をモチーフにした弾幕", "Whiteout_Loop", EnemyPat_Blizzard_DeepSeek },
    { "ChatGPT9", "吹雪をモチーフにした弾幕", "Whiteout_Loop", EnemyPat_Blizzard_ChatGPT },
    { "Gemini9", "吹雪をモチーフにした弾幕", "Whiteout_Loop", EnemyPat_Blizzard_Gemini },
    { "Grok9", "吹雪をモチーフにした弾幕", "Whiteout_Loop", EnemyPat_Blizzard_Grok },
    { "Sakana9", "吹雪をモチーフにした弾幕", "Whiteout_Loop", EnemyPat_Blizzard_Sakana },
    { "Claude9", "吹雪をモチーフにした弾幕", "Whiteout_Loop", EnemyPat_Blizzard_Claude },
    { "Qwen9", "吹雪をモチーフにした弾幕", "Whiteout_Loop", EnemyPat_Blizzard_Qwen },
    { "Vibe9", "吹雪をモチーフにした弾幕", "Whiteout_Loop", EnemyPat_Blizzard_Vibe },
    { "DeepSeek10", "竜をモチーフにした弾幕", "Dragonforge_Overture", EnemyPat_Dragon_DeepSeek },
    { "ChatGPT10", "竜をモチーフにした弾幕", "Dragonforge_Overture", EnemyPat_Dragon_ChatGPT },
    { "Gemini10", "竜をモチーフにした弾幕", "Dragonforge_Overture", EnemyPat_Dragon_Gemini },
    { "Grok10", "竜をモチーフにした弾幕", "Dragonforge_Overture", EnemyPat_Dragon_Grok },
    { "Sakana10", "竜をモチーフにした弾幕", "Dragonforge_Overture", EnemyPat_Dragon_Sakana },
    { "Claude10", "竜をモチーフにした弾幕", "Dragonforge_Overture", EnemyPat_Dragon_Claude },
    { "Qwen10", "竜をモチーフにした弾幕", "Dragonforge_Overture", EnemyPat_Dragon_Qwen },
    { "Vibe10", "竜をモチーフにした弾幕", "Dragonforge_Overture", EnemyPat_Dragon_Vibe },
    { "DeepSeek11", "はかいこうせんをモチーフにした弾幕", "Dragonforge_Overture2", EnemyPat_Hakaikousen_DeepSeek },
    { "ChatGPT11", "はかいこうせんをモチーフにした弾幕", "Dragonforge_Overture2", EnemyPat_Hakaikousen_ChatGPT },
    { "Gemini11", "はかいこうせんをモチーフにした弾幕", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Gemini },
    { "Grok11", "はかいこうせんをモチーフにした弾幕", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Grok },
    { "Sakana11", "はかいこうせんをモチーフにした弾幕", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Sakana },
    { "Claude11", "はかいこうせんをモチーフにした弾幕", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Claude },
    { "Qwen11", "はかいこうせんをモチーフにした弾幕", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Qwen },
    { "Vibe11", "はかいこうせんをモチーフにした弾幕", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Vibe },
    { "DeepSeek12", "太陽をモチーフにした弾幕", "Scorching_Danmaku", EnemyPat_Sun_DeepSeek },
    { "ChatGPT12", "太陽をモチーフにした弾幕", "Scorching_Danmaku", EnemyPat_Sun_ChatGPT },
    { "Gemini12", "太陽をモチーフにした弾幕", "Scorching_Danmaku", EnemyPat_Sun_Gemini },
    { "Grok12", "太陽をモチーフにした弾幕", "Scorching_Danmaku", EnemyPat_Sun_Grok },
    { "Sakana12", "太陽をモチーフにした弾幕", "Scorching_Danmaku", EnemyPat_Sun_Sakana },
    { "Claude12", "太陽をモチーフにした弾幕", "Scorching_Danmaku", EnemyPat_Sun_Claude },
    { "Qwen12", "太陽をモチーフにした弾幕", "Scorching_Danmaku", EnemyPat_Sun_Qwen },
    { "Vibe12", "太陽をモチーフにした弾幕", "Scorching_Danmaku", EnemyPat_Sun_Vibe },
    { "DeepSeek13", "はっぱカッターをモチーフにした弾幕", "Sinnoh_Pulse", EnemyPat_RazorLeaf_DeepSeek },
    { "ChatGPT13", "はっぱカッターをモチーフにした弾幕", "Sinnoh_Pulse", EnemyPat_RazorLeaf_ChatGPT },
    { "Gemini13", "はっぱカッターをモチーフにした弾幕", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Gemini },
    { "Grok13", "はっぱカッターをモチーフにした弾幕", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Grok },
    { "Sakana13", "はっぱカッターをモチーフにした弾幕", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Sakana },
    { "Claude13", "はっぱカッターをモチーフにした弾幕", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Claude },
    { "Qwen13", "はっぱカッターをモチーフにした弾幕", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Qwen },
    { "Vibe13", "はっぱカッターをモチーフにした弾幕", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Vibe },
    { "DeepSeek14", "毒をモチーフにした弾幕", "Toxic_Clockwork", EnemyPat_Poison_DeepSeek },
    { "ChatGPT14", "毒をモチーフにした弾幕", "Toxic_Clockwork", EnemyPat_Poison_ChatGPT },
    { "Gemini14", "毒をモチーフにした弾幕", "Toxic_Clockwork", EnemyPat_Poison_Gemini },
    { "Grok14", "毒をモチーフにした弾幕", "Toxic_Clockwork", EnemyPat_Poison_Grok },
    { "Sakana14", "毒をモチーフにした弾幕", "Toxic_Clockwork", EnemyPat_Poison_Sakana },
    { "Claude14", "毒をモチーフにした弾幕", "Toxic_Clockwork", EnemyPat_Poison_Claude },
    { "Qwen14", "毒をモチーフにした弾幕", "Toxic_Clockwork", EnemyPat_Poison_Qwen },
    { "Vibe14", "毒をモチーフにした弾幕", "Toxic_Clockwork", EnemyPat_Poison_Vibe },
    { "DeepSeek15", "洗濯機をモチーフにした弾幕", "Taiko_Lightning3", EnemyPat_WashingMachine_DeepSeek },
    { "ChatGPT15", "洗濯機をモチーフにした弾幕", "Taiko_Lightning3", EnemyPat_WashingMachine_ChatGPT },
    { "Gemini15", "洗濯機をモチーフにした弾幕", "Taiko_Lightning3", EnemyPat_WashingMachine_Gemini },
    { "Grok15", "洗濯機をモチーフにした弾幕", "Taiko_Lightning3", EnemyPat_WashingMachine_Grok },
    { "Sakana15", "洗濯機をモチーフにした弾幕", "Taiko_Lightning3", EnemyPat_WashingMachine_Sakana },
    { "Claude15", "洗濯機をモチーフにした弾幕", "Taiko_Lightning3", EnemyPat_WashingMachine_Claude },
    { "Qwen15", "洗濯機をモチーフにした弾幕", "Taiko_Lightning3", EnemyPat_WashingMachine_Qwen },
    { "Vibe15", "洗濯機をモチーフにした弾幕", "Taiko_Lightning3", EnemyPat_WashingMachine_Vibe },
    { "DeepSeek16", "囲碁をモチーフにした弾幕", "Bullet_Hell_Shrine", EnemyPat_Go_DeepSeek },
    { "ChatGPT16", "囲碁をモチーフにした弾幕", "Bullet_Hell_Shrine", EnemyPat_Go_ChatGPT },
    { "Gemini16", "囲碁をモチーフにした弾幕", "Bullet_Hell_Shrine", EnemyPat_Go_Gemini },
    { "Grok16", "囲碁をモチーフにした弾幕", "Bullet_Hell_Shrine", EnemyPat_Go_Grok },
    { "Sakana16", "囲碁をモチーフにした弾幕", "Bullet_Hell_Shrine", EnemyPat_Go_Sakana },
    { "Claude16", "囲碁をモチーフにした弾幕", "Bullet_Hell_Shrine", EnemyPat_Go_Claude },
    { "Qwen16", "囲碁をモチーフにした弾幕", "Bullet_Hell_Shrine", EnemyPat_Go_Qwen },
    { "Vibe16", "囲碁をモチーフにした弾幕", "Bullet_Hell_Shrine", EnemyPat_Go_Vibe },
    { "DeepSeek17", "紅葉をモチーフにした弾幕", "Stormleaf_Skyshot", EnemyPat_Maple_DeepSeek },
    { "ChatGPT17", "紅葉をモチーフにした弾幕", "Stormleaf_Skyshot", EnemyPat_Maple_ChatGPT },
    { "Gemini17", "紅葉をモチーフにした弾幕", "Stormleaf_Skyshot", EnemyPat_Maple_Gemini },
    { "Grok17", "紅葉をモチーフにした弾幕", "Stormleaf_Skyshot", EnemyPat_Maple_Grok },
    { "Sakana17", "紅葉をモチーフにした弾幕", "Stormleaf_Skyshot", EnemyPat_Maple_Sakana },
    { "Claude17", "紅葉をモチーフにした弾幕", "Stormleaf_Skyshot", EnemyPat_Maple_Claude },
    { "Qwen17", "紅葉をモチーフにした弾幕", "Stormleaf_Skyshot", EnemyPat_Maple_Qwen },
    { "Vibe17", "紅葉をモチーフにした弾幕", "Stormleaf_Skyshot", EnemyPat_Maple_Vibe },
    { "DeepSeek18", "クモの巣をモチーフにした弾幕", "Toxic_Clockwork2", EnemyPat_SpiderWeb_DeepSeek },
    { "ChatGPT18", "クモの巣をモチーフにした弾幕", "Toxic_Clockwork2", EnemyPat_SpiderWeb_ChatGPT },
    { "Gemini18", "クモの巣をモチーフにした弾幕", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Gemini },
    { "Grok18", "クモの巣をモチーフにした弾幕", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Grok },
    { "Sakana18", "クモの巣をモチーフにした弾幕", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Sakana },
    { "Claude18", "クモの巣をモチーフにした弾幕", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Claude },
    { "Qwen18", "クモの巣をモチーフにした弾幕", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Qwen },
    { "Vibe18", "クモの巣をモチーフにした弾幕", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Vibe },
    { "DeepSeek19", "双曲線をモチーフにした弾幕", "Clockwork_Rush3", EnemyPat_Hyperbola_DeepSeek },
    { "ChatGPT19", "双曲線をモチーフにした弾幕", "Clockwork_Rush3", EnemyPat_Hyperbola_ChatGPT },
    { "Gemini19", "双曲線をモチーフにした弾幕", "Clockwork_Rush3", EnemyPat_Hyperbola_Gemini },
    { "Grok19", "双曲線をモチーフにした弾幕", "Clockwork_Rush3", EnemyPat_Hyperbola_Grok },
    { "Sakana19", "双曲線をモチーフにした弾幕", "Clockwork_Rush3", EnemyPat_Hyperbola_Sakana },
    { "Claude19", "双曲線をモチーフにした弾幕", "Clockwork_Rush3", EnemyPat_Hyperbola_Claude },
    { "Qwen19", "双曲線をモチーフにした弾幕", "Clockwork_Rush3", EnemyPat_Hyperbola_Qwen },
    { "Vibe19", "双曲線をモチーフにした弾幕", "Clockwork_Rush3", EnemyPat_Hyperbola_Vibe },
    { "DeepSeek20", "砂時計をモチーフにした弾幕", "Youma", EnemyPat_Hourglass_DeepSeek },
    { "ChatGPT20", "砂時計をモチーフにした弾幕", "Youma", EnemyPat_Hourglass_ChatGPT },
    { "Gemini20", "砂時計をモチーフにした弾幕", "Youma", EnemyPat_Hourglass_Gemini },
    { "Grok20", "砂時計をモチーフにした弾幕", "Youma", EnemyPat_Hourglass_Grok },
    { "Sakana20", "砂時計をモチーフにした弾幕", "Youma", EnemyPat_Hourglass_Sakana },
    { "Claude20", "砂時計をモチーフにした弾幕", "Youma", EnemyPat_Hourglass_Claude },
    { "Qwen20", "砂時計をモチーフにした弾幕", "Youma", EnemyPat_Hourglass_Qwen },
    { "Vibe20", "砂時計をモチーフにした弾幕", "Youma", EnemyPat_Hourglass_Vibe },
    { "DeepSeek21", "火山をモチーフにした弾幕", "Molten_Crown", EnemyPat_Volcano_DeepSeek },
    { "ChatGPT21", "火山をモチーフにした弾幕", "Molten_Crown", EnemyPat_Volcano_ChatGPT },
    { "Gemini21", "火山をモチーフにした弾幕", "Molten_Crown", EnemyPat_Volcano_Gemini },
    { "Grok21", "火山をモチーフにした弾幕", "Molten_Crown", EnemyPat_Volcano_Grok },
    { "Sakana21", "火山をモチーフにした弾幕", "Molten_Crown", EnemyPat_Volcano_Sakana },
    { "Claude21", "火山をモチーフにした弾幕", "Molten_Crown", EnemyPat_Volcano_Claude },
    { "Qwen21", "火山をモチーフにした弾幕", "Molten_Crown", EnemyPat_Volcano_Qwen },
    { "Vibe21", "火山をモチーフにした弾幕", "Molten_Crown", EnemyPat_Volcano_Vibe },
    { "DeepSeek22", "音ゲーをモチーフにした弾幕", "Organ_Sprint", EnemyPat_RhythmGame_DeepSeek },
    { "ChatGPT22", "音ゲーをモチーフにした弾幕", "Organ_Sprint", EnemyPat_RhythmGame_ChatGPT },
    { "Gemini22", "音ゲーをモチーフにした弾幕", "Organ_Sprint", EnemyPat_RhythmGame_Gemini },
    { "Grok22", "音ゲーをモチーフにした弾幕", "Organ_Sprint", EnemyPat_RhythmGame_Grok },
    { "Sakana22", "音ゲーをモチーフにした弾幕", "Organ_Sprint", EnemyPat_RhythmGame_Sakana },
    { "Claude22", "音ゲーをモチーフにした弾幕", "Organ_Sprint", EnemyPat_RhythmGame_Claude },
    { "Qwen22", "音ゲーをモチーフにした弾幕", "Organ_Sprint", EnemyPat_RhythmGame_Qwen },
    { "Vibe22", "音ゲーをモチーフにした弾幕", "Organ_Sprint", EnemyPat_RhythmGame_Vibe },
    { "DeepSeek23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "Fractal_Boss", EnemyPat_Sierpinski_DeepSeek },
    { "ChatGPT23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "Fractal_Boss", EnemyPat_Sierpinski_ChatGPT },
    { "Gemini23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "Fractal_Boss", EnemyPat_Sierpinski_Gemini },
    { "Grok23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "Fractal_Boss", EnemyPat_Sierpinski_Grok },
    { "Sakana23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "Fractal_Boss", EnemyPat_Sierpinski_Sakana },
    { "Claude23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "Fractal_Boss", EnemyPat_Sierpinski_Claude },
    { "Qwen23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "Fractal_Boss", EnemyPat_Sierpinski_Qwen },
    { "Vibe23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "Fractal_Boss", EnemyPat_Sierpinski_Vibe },
    { "DeepSeek24", "メビウスの帯をモチーフにした弾幕", "Cosmic_Mobius", EnemyPat_Mobius_DeepSeek },
    { "ChatGPT24", "メビウスの帯をモチーフにした弾幕", "Cosmic_Mobius", EnemyPat_Mobius_ChatGPT },
    { "Gemini24", "メビウスの帯をモチーフにした弾幕", "Cosmic_Mobius", EnemyPat_Mobius_Gemini },
    { "Grok24", "メビウスの帯をモチーフにした弾幕", "Cosmic_Mobius", EnemyPat_Mobius_Grok },
    { "Sakana24", "メビウスの帯をモチーフにした弾幕", "Cosmic_Mobius", EnemyPat_Mobius_Sakana },
    { "Claude24", "メビウスの帯をモチーフにした弾幕", "Cosmic_Mobius", EnemyPat_Mobius_Claude },
    { "Qwen24", "メビウスの帯をモチーフにした弾幕", "Cosmic_Mobius", EnemyPat_Mobius_Qwen },
    { "Vibe24", "メビウスの帯をモチーフにした弾幕", "Cosmic_Mobius", EnemyPat_Mobius_Vibe },
    { "DeepSeek25", "扇風機をモチーフにした弾幕", "Frantic_Pulse", EnemyPat_ElectricFan_DeepSeek },
    { "ChatGPT25", "扇風機をモチーフにした弾幕", "Frantic_Pulse", EnemyPat_ElectricFan_ChatGPT },
    { "Gemini25", "扇風機をモチーフにした弾幕", "Frantic_Pulse", EnemyPat_ElectricFan_Gemini },
    { "Grok25", "扇風機をモチーフにした弾幕", "Frantic_Pulse", EnemyPat_ElectricFan_Grok },
    { "Sakana25", "扇風機をモチーフにした弾幕", "Frantic_Pulse", EnemyPat_ElectricFan_Sakana },
    { "Claude25", "扇風機をモチーフにした弾幕", "Frantic_Pulse", EnemyPat_ElectricFan_Claude },
    { "Qwen25", "扇風機をモチーフにした弾幕", "Frantic_Pulse", EnemyPat_ElectricFan_Qwen },
    { "Vibe25", "扇風機をモチーフにした弾幕", "Frantic_Pulse", EnemyPat_ElectricFan_Vibe },
    { "DeepSeek26", "文字を活用した弾幕", "Shamisen_Run", EnemyPat_Moji_DeepSeek },
    { "ChatGPT26", "文字を活用した弾幕", "Shamisen_Run", EnemyPat_Moji_ChatGPT },
    { "Gemini26", "文字を活用した弾幕", "Shamisen_Run", EnemyPat_Moji_Gemini },
    { "Grok26", "文字を活用した弾幕", "Shamisen_Run", EnemyPat_Moji_Grok },
    { "Sakana26", "文字を活用した弾幕", "Shamisen_Run", EnemyPat_Moji_Sakana },
    { "Claude26", "文字を活用した弾幕", "Shamisen_Run", EnemyPat_Moji_Claude },
    { "Qwen26", "文字を活用した弾幕", "Shamisen_Run", EnemyPat_Moji_Qwen },
    { "Vibe26", "文字を活用した弾幕", "Shamisen_Run", EnemyPat_Moji_Vibe },
    { "DeepSeek27", "手裏剣をモチーフにした弾幕", "Gongline_Riot", EnemyPat_Shuriken_DeepSeek },
    { "ChatGPT27", "手裏剣をモチーフにした弾幕", "Gongline_Riot", EnemyPat_Shuriken_ChatGPT },
    { "Gemini27", "手裏剣をモチーフにした弾幕", "Gongline_Riot", EnemyPat_Shuriken_Gemini },
    { "Grok27", "手裏剣をモチーフにした弾幕", "Gongline_Riot", EnemyPat_Shuriken_Grok },
    { "Sakana27", "手裏剣をモチーフにした弾幕", "Gongline_Riot", EnemyPat_Shuriken_Sakana },
    { "Claude27", "手裏剣をモチーフにした弾幕", "Gongline_Riot", EnemyPat_Shuriken_Claude },
    { "Qwen27", "手裏剣をモチーフにした弾幕", "Gongline_Riot", EnemyPat_Shuriken_Qwen },
    { "Vibe27", "手裏剣をモチーフにした弾幕", "Gongline_Riot", EnemyPat_Shuriken_Vibe },
    { "DeepSeek28", "金閣寺の一枚天井", "Gongline_Riot2", EnemyPat_Kinkakuji_DeepSeek },
    { "ChatGPT28", "金閣寺の一枚天井", "Gongline_Riot2", EnemyPat_Kinkakuji_ChatGPT },
    { "Gemini28", "金閣寺の一枚天井", "Gongline_Riot2", EnemyPat_Kinkakuji_Gemini },
    { "Grok28", "金閣寺の一枚天井", "Gongline_Riot2", EnemyPat_Kinkakuji_Grok },
    { "Sakana28", "金閣寺の一枚天井", "Gongline_Riot2", EnemyPat_Kinkakuji_Sakana },
    { "Claude28", "金閣寺の一枚天井", "Gongline_Riot2", EnemyPat_Kinkakuji_Claude },
    { "Qwen28", "金閣寺の一枚天井", "Gongline_Riot2", EnemyPat_Kinkakuji_Qwen },
    { "Vibe28", "金閣寺の一枚天井", "Gongline_Riot2", EnemyPat_Kinkakuji_Vibe },
    { "DeepSeek29", "シャボン玉をモチーフにした弾幕", "Bubble_Horizon", EnemyPat_SoapBubbles_DeepSeek },
    { "ChatGPT29", "シャボン玉をモチーフにした弾幕", "Bubble_Horizon", EnemyPat_SoapBubbles_ChatGPT },
    { "Gemini29", "シャボン玉をモチーフにした弾幕", "Bubble_Horizon", EnemyPat_SoapBubbles_Gemini },
    { "Grok29", "シャボン玉をモチーフにした弾幕", "Bubble_Horizon", EnemyPat_SoapBubbles_Grok },
    { "Sakana29", "シャボン玉をモチーフにした弾幕", "Bubble_Horizon", EnemyPat_SoapBubbles_Sakana },
    { "Claude29", "シャボン玉をモチーフにした弾幕", "Bubble_Horizon", EnemyPat_SoapBubbles_Claude },
    { "Qwen29", "シャボン玉をモチーフにした弾幕", "Bubble_Horizon", EnemyPat_SoapBubbles_Qwen },
    { "Vibe29", "シャボン玉をモチーフにした弾幕", "Bubble_Horizon", EnemyPat_SoapBubbles_Vibe },
    { "DeepSeek30", "ショットガンをモチーフにした弾幕", "Torque_Anthem", EnemyPat_Shotgun_DeepSeek },
    { "ChatGPT30", "ショットガンをモチーフにした弾幕", "Torque_Anthem", EnemyPat_Shotgun_ChatGPT },
    { "Gemini30", "ショットガンをモチーフにした弾幕", "Torque_Anthem", EnemyPat_Shotgun_Gemini },
    { "Grok30", "ショットガンをモチーフにした弾幕", "Torque_Anthem", EnemyPat_Shotgun_Grok },
    { "Sakana30", "ショットガンをモチーフにした弾幕", "Torque_Anthem", EnemyPat_Shotgun_Sakana },
    { "Claude30", "ショットガンをモチーフにした弾幕", "Torque_Anthem", EnemyPat_Shotgun_Claude },
    { "Qwen30", "ショットガンをモチーフにした弾幕", "Torque_Anthem", EnemyPat_Shotgun_Qwen },
    { "Kimi30", "ショットガンをモチーフにした弾幕", "Torque_Anthem", EnemyPat_Shotgun_Kimi },
    { "DeepSeek31", "戻り弾幕", "Youma2", EnemyPat_Reverse_DeepSeek },
    { "ChatGPT31", "戻り弾幕", "Youma2", EnemyPat_Reverse_ChatGPT },
    { "Gemini31", "戻り弾幕", "Youma2", EnemyPat_Reverse_Gemini },
    { "Grok31", "戻り弾幕", "Youma2", EnemyPat_Reverse_Grok },
    { "Sakana31", "戻り弾幕", "Youma2", EnemyPat_Reverse_Sakana },
    { "Claude31", "戻り弾幕", "Youma2", EnemyPat_Reverse_Claude },
    { "Qwen31", "戻り弾幕", "Youma2", EnemyPat_Reverse_Qwen },
    { "Kimi31", "戻り弾幕", "Youma2", EnemyPat_Reverse_Kimi },
    { "DeepSeek32", "ボンバーマンをモチーフにした弾幕", "Pixel_Victory_Run", EnemyPat_Bomberman_DeepSeek },
    { "ChatGPT32", "ボンバーマンをモチーフにした弾幕", "Pixel_Victory_Run", EnemyPat_Bomberman_ChatGPT },
    { "Gemini32", "ボンバーマンをモチーフにした弾幕", "Pixel_Victory_Run", EnemyPat_Bomberman_Gemini },
    { "Grok32", "ボンバーマンをモチーフにした弾幕", "Pixel_Victory_Run", EnemyPat_Bomberman_Grok },
    { "Sakana32", "ボンバーマンをモチーフにした弾幕", "Pixel_Victory_Run", EnemyPat_Bomberman_Sakana },
    { "Claude32", "ボンバーマンをモチーフにした弾幕", "Pixel_Victory_Run", EnemyPat_Bomberman_Claude },
    { "Qwen32", "ボンバーマンをモチーフにした弾幕", "Pixel_Victory_Run", EnemyPat_Bomberman_Qwen },
    { "Kimi32", "ボンバーマンをモチーフにした弾幕", "Pixel_Victory_Run", EnemyPat_Bomberman_Kimi },
    { "DeepSeek33", "回避不可能な弾幕", "Torpedo_Hymn", EnemyPat_Unavoidable_DeepSeek },
    { "ChatGPT33", "回避不可能な弾幕", "Torpedo_Hymn", EnemyPat_Unavoidable_ChatGPT },
    { "Gemini33", "回避不可能な弾幕", "Torpedo_Hymn", EnemyPat_Unavoidable_Gemini },
    { "Grok33", "回避不可能な弾幕", "Torpedo_Hymn", EnemyPat_Unavoidable_Grok },
    { "Sakana33", "回避不可能な弾幕", "Torpedo_Hymn", EnemyPat_Unavoidable_Sakana },
    { "Claude33", "回避不可能な弾幕", "Torpedo_Hymn", EnemyPat_Unavoidable_Claude },
    { "Qwen33", "回避不可能な弾幕", "Torpedo_Hymn", EnemyPat_Unavoidable_Qwen },
    { "Kimi33", "回避不可能な弾幕", "Torpedo_Hymn", EnemyPat_Unavoidable_Kimi },
    { "DeepSeek34", "マッチをモチーフにした弾幕", "Kagura_Storm", EnemyPat_Match_DeepSeek },
    { "ChatGPT34", "マッチをモチーフにした弾幕", "Kagura_Storm", EnemyPat_Match_ChatGPT },
    { "Gemini34", "マッチをモチーフにした弾幕", "Kagura_Storm", EnemyPat_Match_Gemini },
    { "Grok34", "マッチをモチーフにした弾幕", "Kagura_Storm", EnemyPat_Match_Grok },
    { "Sakana34", "マッチをモチーフにした弾幕", "Kagura_Storm", EnemyPat_Match_Sakana },
    { "Claude34", "マッチをモチーフにした弾幕", "Kagura_Storm", EnemyPat_Match_Claude },
    { "Qwen34", "マッチをモチーフにした弾幕", "Kagura_Storm", EnemyPat_Match_Qwen },
    { "Kimi34", "マッチをモチーフにした弾幕", "Kagura_Storm", EnemyPat_Match_Kimi },
    { "DeepSeek35", "ワインダーを活用した弾幕", "Spellbound_Bamboo_Rush", EnemyPat_Winder_DeepSeek },
    { "ChatGPT35", "ワインダーを活用した弾幕", "Spellbound_Bamboo_Rush", EnemyPat_Winder_ChatGPT },
    { "Gemini35", "ワインダーを活用した弾幕", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Gemini },
    { "Grok35", "ワインダーを活用した弾幕", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Grok },
    { "Sakana35", "ワインダーを活用した弾幕", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Sakana },
    { "Claude35", "ワインダーを活用した弾幕", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Claude },
    { "Qwen35", "ワインダーを活用した弾幕", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Qwen },
    { "Kimi35", "ワインダーを活用した弾幕", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Kimi },
    { "DeepSeek36", "ポップコーンをモチーフにした弾幕", "Pixel_Pop_Panic", EnemyPat_Popcorn_DeepSeek },
    { "ChatGPT36", "ポップコーンをモチーフにした弾幕", "Pixel_Pop_Panic", EnemyPat_Popcorn_ChatGPT },
    { "Gemini36", "ポップコーンをモチーフにした弾幕", "Pixel_Pop_Panic", EnemyPat_Popcorn_Gemini },
    { "Grok36", "ポップコーンをモチーフにした弾幕", "Pixel_Pop_Panic", EnemyPat_Popcorn_Grok },
    { "Sakana36", "ポップコーンをモチーフにした弾幕", "Pixel_Pop_Panic", EnemyPat_Popcorn_Sakana },
    { "Claude36", "ポップコーンをモチーフにした弾幕", "Pixel_Pop_Panic", EnemyPat_Popcorn_Claude },
    { "Qwen36", "ポップコーンをモチーフにした弾幕", "Pixel_Pop_Panic", EnemyPat_Popcorn_Qwen },
    { "Kimi36", "ポップコーンをモチーフにした弾幕", "Pixel_Pop_Panic", EnemyPat_Popcorn_Kimi },
    { "DeepSeek37", "立体的に見える弾幕", "Sphere_Breaker", EnemyPat_3D_DeepSeek },
    { "ChatGPT37", "立体的に見える弾幕", "Sphere_Breaker", EnemyPat_3D_ChatGPT },
    { "Gemini37", "立体的に見える弾幕", "Sphere_Breaker", EnemyPat_3D_Gemini },
    { "Grok37", "立体的に見える弾幕", "Sphere_Breaker", EnemyPat_3D_Grok },
    { "Sakana37", "立体的に見える弾幕", "Sphere_Breaker", EnemyPat_3D_Sakana },
    { "Claude37", "立体的に見える弾幕", "Sphere_Breaker", EnemyPat_3D_Claude },
    { "Qwen37", "立体的に見える弾幕", "Sphere_Breaker", EnemyPat_3D_Qwen },
    { "Kimi37", "立体的に見える弾幕", "Sphere_Breaker", EnemyPat_3D_Kimi },
    { "DeepSeek38", "レーザーを活用した弾幕", "Cage_Of_Lasers", EnemyPat_Laser_DeepSeek },
    { "ChatGPT38", "レーザーを活用した弾幕", "Cage_Of_Lasers", EnemyPat_Laser_ChatGPT },
    { "Gemini38", "レーザーを活用した弾幕", "Cage_Of_Lasers", EnemyPat_Laser_Gemini },
    { "Grok38", "レーザーを活用した弾幕", "Cage_Of_Lasers", EnemyPat_Laser_Grok },
    { "Sakana38", "レーザーを活用した弾幕", "Cage_Of_Lasers", EnemyPat_Laser_Sakana },
    { "Claude38", "レーザーを活用した弾幕", "Cage_Of_Lasers", EnemyPat_Laser_Claude },
    { "Qwen38", "レーザーを活用した弾幕", "Cage_Of_Lasers", EnemyPat_Laser_Qwen },
    { "Kimi38", "レーザーを活用した弾幕", "Cage_Of_Lasers", EnemyPat_Laser_Kimi },
    { "DeepSeek39", "インベーダーゲームをモチーフにした弾幕", "Quiet_Opening", EnemyPat_Invader_DeepSeek },
    { "ChatGPT39", "インベーダーゲームをモチーフにした弾幕", "Quiet_Opening", EnemyPat_Invader_ChatGPT },
    { "Gemini39", "インベーダーゲームをモチーフにした弾幕", "Quiet_Opening", EnemyPat_Invader_Gemini },
    { "Grok39", "インベーダーゲームをモチーフにした弾幕", "Quiet_Opening", EnemyPat_Invader_Grok },
    { "Sakana39", "インベーダーゲームをモチーフにした弾幕", "Quiet_Opening", EnemyPat_Invader_Sakana },
    { "Claude39", "インベーダーゲームをモチーフにした弾幕", "Quiet_Opening", EnemyPat_Invader_Claude },
    { "Qwen39", "インベーダーゲームをモチーフにした弾幕", "Quiet_Opening", EnemyPat_Invader_Qwen },
    { "Kimi39", "インベーダーゲームをモチーフにした弾幕", "Quiet_Opening", EnemyPat_Invader_Kimi },
    { "DeepSeek40", "二重振り子をモチーフにした弾幕", "Pendulum_Chaos", EnemyPat_DoublePendulum_DeepSeek },
    { "ChatGPT40", "二重振り子をモチーフにした弾幕", "Pendulum_Chaos", EnemyPat_DoublePendulum_ChatGPT },
    { "Gemini40", "二重振り子をモチーフにした弾幕", "Pendulum_Chaos", EnemyPat_DoublePendulum_Gemini },
    { "Grok40", "二重振り子をモチーフにした弾幕", "Pendulum_Chaos", EnemyPat_DoublePendulum_Grok },
    { "Sakana40", "二重振り子をモチーフにした弾幕", "Pendulum_Chaos", EnemyPat_DoublePendulum_Sakana },
    { "Claude40", "二重振り子をモチーフにした弾幕", "Pendulum_Chaos", EnemyPat_DoublePendulum_Claude },
    { "Qwen40", "二重振り子をモチーフにした弾幕", "Pendulum_Chaos", EnemyPat_DoublePendulum_Qwen },
    { "Kimi40", "二重振り子をモチーフにした弾幕", "Pendulum_Chaos", EnemyPat_DoublePendulum_Kimi },
    { "DeepSeek41", "ブロック崩しをモチーフにした弾幕", "Quiet_Opening2", EnemyPat_BlockBreak_DeepSeek },
    { "ChatGPT41", "ブロック崩しをモチーフにした弾幕", "Quiet_Opening2", EnemyPat_BlockBreak_ChatGPT },
    { "Gemini41", "ブロック崩しをモチーフにした弾幕", "Quiet_Opening2", EnemyPat_BlockBreak_Gemini },
    { "Grok41", "ブロック崩しをモチーフにした弾幕", "Quiet_Opening2", EnemyPat_BlockBreak_Grok },
    { "Sakana41", "ブロック崩しをモチーフにした弾幕", "Quiet_Opening2", EnemyPat_BlockBreak_Sakana },
    { "Claude41", "ブロック崩しをモチーフにした弾幕", "Quiet_Opening2", EnemyPat_BlockBreak_Claude },
    { "Qwen41", "ブロック崩しをモチーフにした弾幕", "Quiet_Opening2", EnemyPat_BlockBreak_Qwen },
    { "Kimi41", "ブロック崩しをモチーフにした弾幕", "Quiet_Opening2", EnemyPat_BlockBreak_Kimi },
    { "DeepSeek42", "ピラミッドをモチーフにした弾幕", "Desert_Storm", EnemyPat_Pyramid_DeepSeek },
    { "ChatGPT42", "ピラミッドをモチーフにした弾幕", "Desert_Storm", EnemyPat_Pyramid_ChatGPT },
    { "Gemini42", "ピラミッドをモチーフにした弾幕", "Desert_Storm", EnemyPat_Pyramid_Gemini },
    { "Grok42", "ピラミッドをモチーフにした弾幕", "Desert_Storm", EnemyPat_Pyramid_Grok },
    { "Claude42", "ピラミッドをモチーフにした弾幕", "Desert_Storm", EnemyPat_Pyramid_Claude },
    { "Qwen42", "ピラミッドをモチーフにした弾幕", "Desert_Storm", EnemyPat_Pyramid_Qwen },
    { "Kimi42", "ピラミッドをモチーフにした弾幕", "Desert_Storm", EnemyPat_Pyramid_Kimi },
    { "Zai42", "ピラミッドをモチーフにした弾幕", "Desert_Storm", EnemyPat_Pyramid_Zai },
    { "DeepSeek43", "ボスが体当たりしてくる弾幕", "Cathedral_Ashes", EnemyPat_Tackle_DeepSeek },
    { "ChatGPT43", "ボスが体当たりしてくる弾幕", "Cathedral_Ashes", EnemyPat_Tackle_ChatGPT },
    { "Gemini43", "ボスが体当たりしてくる弾幕", "Cathedral_Ashes", EnemyPat_Tackle_Gemini },
    { "Grok43", "ボスが体当たりしてくる弾幕", "Cathedral_Ashes", EnemyPat_Tackle_Grok },
    { "Claude43", "ボスが体当たりしてくる弾幕", "Cathedral_Ashes", EnemyPat_Tackle_Claude },
    { "Qwen43", "ボスが体当たりしてくる弾幕", "Cathedral_Ashes", EnemyPat_Tackle_Qwen },
    { "Kimi43", "ボスが体当たりしてくる弾幕", "Cathedral_Ashes", EnemyPat_Tackle_Kimi },
    { "Zai43", "ボスが体当たりしてくる弾幕", "Cathedral_Ashes", EnemyPat_Tackle_Zai },
    { "DeepSeek44", "矢印をモチーフにした弾幕", "Arrow_Circuit", EnemyPat_Arrow_DeepSeek },
    { "ChatGPT44", "矢印をモチーフにした弾幕", "Arrow_Circuit", EnemyPat_Arrow_ChatGPT },
    { "Gemini44", "矢印をモチーフにした弾幕", "Arrow_Circuit", EnemyPat_Arrow_Gemini },
    { "Grok44", "矢印をモチーフにした弾幕", "Arrow_Circuit", EnemyPat_Arrow_Grok },
    { "Claude44", "矢印をモチーフにした弾幕", "Arrow_Circuit", EnemyPat_Arrow_Claude },
    { "Qwen44", "矢印をモチーフにした弾幕", "Arrow_Circuit", EnemyPat_Arrow_Qwen },
    { "Kimi44", "矢印をモチーフにした弾幕", "Arrow_Circuit", EnemyPat_Arrow_Kimi },
    { "Zai44", "矢印をモチーフにした弾幕", "Arrow_Circuit", EnemyPat_Arrow_Zai },
    { "DeepSeek45", "DNAをモチーフにした弾幕", "Helix_Test_Tube", EnemyPat_DNA_DeepSeek },
    { "ChatGPT45", "DNAをモチーフにした弾幕", "Helix_Test_Tube", EnemyPat_DNA_ChatGPT },
    { "Gemini45", "DNAをモチーフにした弾幕", "Helix_Test_Tube", EnemyPat_DNA_Gemini },
    { "Grok45", "DNAをモチーフにした弾幕", "Helix_Test_Tube", EnemyPat_DNA_Grok },
    { "Claude45", "DNAをモチーフにした弾幕", "Helix_Test_Tube", EnemyPat_DNA_Claude },
    { "Qwen45", "DNAをモチーフにした弾幕", "Helix_Test_Tube", EnemyPat_DNA_Qwen },
    { "Kimi45", "DNAをモチーフにした弾幕", "Helix_Test_Tube", EnemyPat_DNA_Kimi },
    { "Zai45", "DNAをモチーフにした弾幕", "Helix_Test_Tube", EnemyPat_DNA_Zai },
    { "DeepSeek46", "大砂嵐をモチーフにした弾幕", "Neon_Dune_Rush", EnemyPat_SandStorm_DeepSeek },
    { "ChatGPT46", "大砂嵐をモチーフにした弾幕", "Neon_Dune_Rush", EnemyPat_SandStorm_ChatGPT },
    { "Gemini46", "大砂嵐をモチーフにした弾幕", "Neon_Dune_Rush", EnemyPat_SandStorm_Gemini },
    { "Grok46", "大砂嵐をモチーフにした弾幕", "Neon_Dune_Rush", EnemyPat_SandStorm_Grok },
    { "Claude46", "大砂嵐をモチーフにした弾幕", "Neon_Dune_Rush", EnemyPat_SandStorm_Claude },
    { "Qwen46", "大砂嵐をモチーフにした弾幕", "Neon_Dune_Rush", EnemyPat_SandStorm_Qwen },
    { "Kimi46", "大砂嵐をモチーフにした弾幕", "Neon_Dune_Rush", EnemyPat_SandStorm_Kimi },
    { "Zai46", "大砂嵐をモチーフにした弾幕", "Neon_Dune_Rush", EnemyPat_SandStorm_Zai },
    { "DeepSeek47", "へにょりレーザーを用いた弾幕", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_DeepSeek },
    { "ChatGPT47", "へにょりレーザーを用いた弾幕", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_ChatGPT },
    { "Gemini47", "へにょりレーザーを用いた弾幕", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Gemini },
    { "Grok47", "へにょりレーザーを用いた弾幕", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Grok },
    { "Claude47", "へにょりレーザーを用いた弾幕", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Claude },
    { "Qwen47", "へにょりレーザーを用いた弾幕", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Qwen },
    { "Kimi47", "へにょりレーザーを用いた弾幕", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Kimi },
    { "Zai47", "へにょりレーザーを用いた弾幕", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Zai },
    { "DeepSeek48", "潮吹きをモチーフにした弾幕", "Tidal Ascend", EnemyPat_Spout_DeepSeek },
    { "ChatGPT48", "潮吹きをモチーフにした弾幕", "Tidal Ascend", EnemyPat_Spout_ChatGPT },
    { "Gemini48", "潮吹きをモチーフにした弾幕", "Tidal Ascend", EnemyPat_Spout_Gemini },
    { "Grok48", "潮吹きをモチーフにした弾幕", "Tidal Ascend", EnemyPat_Spout_Grok },
    { "Claude48", "潮吹きをモチーフにした弾幕", "Tidal Ascend", EnemyPat_Spout_Claude },
    { "Qwen48", "潮吹きをモチーフにした弾幕", "Tidal Ascend", EnemyPat_Spout_Qwen },
    { "Sakana48", "潮吹きをモチーフにした弾幕", "Tidal Ascend", EnemyPat_Spout_Sakana },
    { "Zai48", "潮吹きをモチーフにした弾幕", "Tidal Ascend", EnemyPat_Spout_Zai },
    { "DeepSeek49", "ライフゲームをモチーフにした弾幕", "Digital Grid Run", EnemyPat_LifeGame_DeepSeek },
    { "ChatGPT49", "ライフゲームをモチーフにした弾幕", "Digital Grid Run", EnemyPat_LifeGame_ChatGPT },
    { "Gemini49", "ライフゲームをモチーフにした弾幕", "Digital Grid Run", EnemyPat_LifeGame_Gemini },
    { "Grok49", "ライフゲームをモチーフにした弾幕", "Digital Grid Run", EnemyPat_LifeGame_Grok },
    { "Claude49", "ライフゲームをモチーフにした弾幕", "Digital Grid Run", EnemyPat_LifeGame_Claude },
    { "Qwen49", "ライフゲームをモチーフにした弾幕", "Digital Grid Run", EnemyPat_LifeGame_Qwen },
    { "Kimi49", "ライフゲームをモチーフにした弾幕", "Digital Grid Run", EnemyPat_LifeGame_Kimi },
    { "Zai49", "ライフゲームをモチーフにした弾幕", "Digital Grid Run", EnemyPat_LifeGame_Zai },
    { "DeepSeek50", "スイミーをモチーフにした弾幕", "Shoal Storm Run", EnemyPat_Swimmy_DeepSeek },
    { "ChatGPT50", "スイミーをモチーフにした弾幕", "Shoal Storm Run", EnemyPat_Swimmy_ChatGPT },
    { "Gemini50", "スイミーをモチーフにした弾幕", "Shoal Storm Run", EnemyPat_Swimmy_Gemini },
    { "Grok50", "スイミーをモチーフにした弾幕", "Shoal Storm Run", EnemyPat_Swimmy_Grok },
    { "Claude50", "スイミーをモチーフにした弾幕", "Shoal Storm Run", EnemyPat_Swimmy_Claude },
    { "Qwen50", "スイミーをモチーフにした弾幕", "Shoal Storm Run", EnemyPat_Swimmy_Qwen },
    { "Kimi50", "スイミーをモチーフにした弾幕", "Shoal Storm Run", EnemyPat_Swimmy_Kimi },
    { "Zai50", "スイミーをモチーフにした弾幕", "Shoal Storm Run", EnemyPat_Swimmy_Zai },
    { "tmp", "ここに貼ってお試し", "Torpedo_Hymn", EnemyPat_Tmp },
};