// stageData.cpp
#include "stageData.h"

std::vector<StageInfo> stageData = {
    // stageId, description, stageTitle, bgmFileName, patternFunc
    { "sample", "AIに渡すためのサンプル。使える素材の一覧を教える", "", "field", EnemyPat_SampleForAI },
    { "handmade1", "3WAY自機狙い", "", "Torpedo_Hymn2", EnemyPat_3Way },
    { "handmade2", "全方位", "", "Torpedo_Hymn2", EnemyPat_Round },
    { "handmade3", "破裂弾", "", "Torpedo_Hymn2", EnemyPat_Burst },
    { "handmade4", "波と粒の境界（目コピ）", "", "Torpedo_Hymn2", EnemyPat_Namitsubu },
    { "handmade5", "ドーブルをモチーフにした弾幕。くろいまなざし→キノコのほうし→ロックオン→つのドリル", "画符「スケッチ・オブ・デス」", "Torpedo_Hymn2", EnemyPat_Smeargle },
    { "handmade6", "世界のナベアツをモチーフにした弾幕", "数符「デジタル・アホリズム」", "Flying Futon Frenzy 2", EnemyPat_Nabeatsu },
    { "ClaudeEX1", "高難易度の弾幕", "", "Torpedo_Hymn", EnemyPat_Difficulty_Claude },
    { "ClaudeEX2", "幾何学的に美しい弾幕 アナザー", "", "Torpedo_Hymn", EnemyPat_Geometry_Claude2 },
    { "GrokEX1", "彗星をモチーフにした弾幕 アナザー", "", "Torpedo_Hymn", EnemyPat_Comet_Grok2 },
    { "GeminiEx1", "達人王みたいな弾幕", "", "Torpedo_Hymn", EnemyPat_Tatsujinou_Gemini },
    { "DeepSeekEx2", "はっぱカッターをモチーフにした弾幕 アナザー", "", "Torpedo_Hymn", EnemyPat_RazorLeaf_DeepSeek2 },
    { "ClaudeEx3", "達人王みたいな弾幕", "", "Torpedo_Hymn", EnemyPat_Tatsujinou_Claude },
    { "ClaudeEx4", "蜂をモチーフにした弾幕 アナザー", "", "Torpedo_Hymn", EnemyPat_Bee_Claude2 },
    { "GeminiEx2", "闇符「ディマーケイション」LUNATIC", "", "Torpedo_Hymn", EnemyPat_Demarcation_Gemini },
    { "GeminiEx3", "魔法のランプをモチーフにした弾幕", "", "Desert Lamp Pursuit", EnemyPat_MagicLamp_Gemini },
    { "DeepSeek", "幾何学的に美しい弾幕", "", "Chrome_Synapse", EnemyPat_Geometry_DeepSeek },
    { "ChatGPT", "幾何学的に美しい弾幕", "万華鏡リサージュ", "Chrome_Synapse", EnemyPat_Geometry_ChatGPT },
    { "Gemini", "幾何学的に美しい弾幕", "", "Chrome_Synapse", EnemyPat_Geometry_Gemini },
    { "Grok", "幾何学的に美しい弾幕", "", "Chrome_Synapse", EnemyPat_Geometry_Grok },
    { "Sakana", "幾何学的に美しい弾幕", "", "Chrome_Synapse", EnemyPat_Geometry_Sakana },
    { "Claude", "幾何学的に美しい弾幕", "フィボナッチ螺旋弾幕「ひまわり」", "Chrome_Synapse", EnemyPat_Geometry_Claude },
    { "Qwen", "幾何学的に美しい弾幕", "", "Chrome_Synapse", EnemyPat_Geometry_Qwen },
    { "Vibe", "幾何学的に美しい弾幕", "", "Chrome_Synapse", EnemyPat_Geometry_Vibe },
    { "DeepSeek2", "避けていて楽しい弾幕", "", "Polished_Thunder", EnemyPat_Dodge_DeepSeek },
    { "ChatGPT2", "避けていて楽しい弾幕", "誘導の狭間", "Polished_Thunder", EnemyPat_Dodge_ChatGPT },
    { "Gemini2", "避けていて楽しい弾幕", "時限一斉収縮ターゲット弾「サイレンス・トラップ」", "Polished_Thunder", EnemyPat_Dodge_Gemini },
    { "Grok2", "避けていて楽しい弾幕", "", "Polished_Thunder", EnemyPat_Dodge_Grok },
    { "Sakana2", "避けていて楽しい弾幕", "", "Polished_Thunder", EnemyPat_Dodge_Sakana },
    { "Claude2", "避けていて楽しい弾幕", "", "Polished_Thunder", EnemyPat_Dodge_Claude },
    { "Qwen2", "避けていて楽しい弾幕", "", "Polished_Thunder", EnemyPat_Dodge_Qwen },
    { "Vibe2", "避けていて楽しい弾幕", "", "Polished_Thunder", EnemyPat_Dodge_Vibe },
    { "DeepSeek3", "見栄えのいい弾幕", "レインボースパイラル", "Chromed_Halo", EnemyPat_Beautiful_DeepSeek },
    { "ChatGPT3", "見栄えのいい弾幕", "花渦輪舞", "Chromed_Halo", EnemyPat_Beautiful_ChatGPT },
    { "Gemini3", "見栄えのいい弾幕", "", "Chromed_Halo", EnemyPat_Beautiful_Gemini },
    { "Grok3", "見栄えのいい弾幕", "", "Chromed_Halo", EnemyPat_Beautiful_Grok },
    { "Sakana3", "見栄えのいい弾幕", "", "Chromed_Halo", EnemyPat_Beautiful_Sakana },
    { "Claude3", "見栄えのいい弾幕", "", "Chromed_Halo", EnemyPat_Beautiful_Claude },
    { "Qwen3", "見栄えのいい弾幕", "", "Chromed_Halo", EnemyPat_Beautiful_Qwen },
    { "Vibe3", "見栄えのいい弾幕", "", "Chromed_Halo", EnemyPat_Beautiful_Vibe },
    { "DeepSeek4", "和風な弾幕", "", "Taiko_Lightning", EnemyPat_Japanese_DeepSeek },
    { "ChatGPT4", "和風な弾幕", "花嵐扇舞", "Taiko_Lightning", EnemyPat_Japanese_ChatGPT },
    { "Gemini4", "和風な弾幕", "", "Taiko_Lightning", EnemyPat_Japanese_Gemini },
    { "Grok4", "和風な弾幕", "", "Taiko_Lightning", EnemyPat_Japanese_Grok },
    { "Sakana4", "和風な弾幕", "", "Taiko_Lightning", EnemyPat_Japanese_Sakana },
    { "Claude4", "和風な弾幕", "", "Taiko_Lightning", EnemyPat_Japanese_Claude },
    { "Qwen4", "和風な弾幕", "", "Taiko_Lightning", EnemyPat_Japanese_Qwen },
    { "Vibe4", "和風な弾幕", "", "Taiko_Lightning", EnemyPat_Japanese_Vibe },
    { "DeepSeek5", "滝をモチーフにした弾幕", "", "Taiko_Lightning2", EnemyPat_Waterfall_DeepSeek },
    { "ChatGPT5", "滝をモチーフにした弾幕", "蒼瀑「天泣の大瀑布」", "Taiko_Lightning2", EnemyPat_Waterfall_ChatGPT },
    { "Gemini5", "滝をモチーフにした弾幕", "滝符『白糸の瀑布』", "Taiko_Lightning2", EnemyPat_Waterfall_Gemini },
    { "Grok5", "滝をモチーフにした弾幕", "", "Taiko_Lightning2", EnemyPat_Waterfall_Grok },
    { "Sakana5", "滝をモチーフにした弾幕", "", "Taiko_Lightning2", EnemyPat_Waterfall_Sakana },
    { "Claude5", "滝をモチーフにした弾幕", "", "Taiko_Lightning2", EnemyPat_Waterfall_Claude },
    { "Qwen5", "滝をモチーフにした弾幕", "", "Taiko_Lightning2", EnemyPat_Waterfall_Qwen },
    { "Vibe5", "滝をモチーフにした弾幕", "", "Taiko_Lightning2", EnemyPat_Waterfall_Vibe },
    { "DeepSeek6", "波と粒の境界", "", "Clockwork_Rush", EnemyPat_Namistubu_DeepSeek },
    { "ChatGPT6", "波と粒の境界", "波際の粒界線", "Clockwork_Rush", EnemyPat_Namistubu_ChatGPT },
    { "Gemini6", "波と粒の境界", "", "Clockwork_Rush", EnemyPat_Namistubu_Gemini },
    { "Grok6", "波と粒の境界", "境符「回転する波と粒」", "Clockwork_Rush", EnemyPat_Namistubu_Grok },
    { "Sakana6", "波と粒の境界", "", "Clockwork_Rush", EnemyPat_Namistubu_Sakana },
    { "Claude6", "波と粒の境界", "", "Clockwork_Rush", EnemyPat_Namistubu_Claude },
    { "Qwen6", "波と粒の境界", "", "Clockwork_Rush", EnemyPat_Namistubu_Qwen },
    { "Vibe6", "波と粒の境界", "", "Clockwork_Rush", EnemyPat_Namitsubu_Vibe },
    { "DeepSeek7", "彗星をモチーフにした弾幕", "", "Nebula_Pulse_Loop", EnemyPat_Comet_DeepSeek },
    { "ChatGPT7", "彗星をモチーフにした弾幕", "尾を曳く蒼天の彗星", "Nebula_Pulse_Loop", EnemyPat_Comet_ChatGPT },
    { "Gemini7", "彗星をモチーフにした弾幕", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Gemini },
    { "Grok7", "彗星をモチーフにした弾幕", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Grok },
    { "Sakana7", "彗星をモチーフにした弾幕", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Sakana },
    { "Claude7", "彗星をモチーフにした弾幕", "彗星の軌跡", "Nebula_Pulse_Loop", EnemyPat_Comet_Claude },
    { "Qwen7", "彗星をモチーフにした弾幕", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Qwen },
    { "Vibe7", "彗星をモチーフにした弾幕", "", "Nebula_Pulse_Loop", EnemyPat_Comet_Vibe },
    { "DeepSeek8", "雷をモチーフにした弾幕", "", "Clockwork_Rush2", EnemyPat_Thunder_DeepSeek },
    { "ChatGPT8", "雷をモチーフにした弾幕", "雷鳴裂走（らいめいれっそう）", "Clockwork_Rush2", EnemyPat_Thunder_ChatGPT },
    { "Gemini8", "雷をモチーフにした弾幕", "", "Clockwork_Rush2", EnemyPat_Thunder_Gemini },
    { "Grok8", "雷をモチーフにした弾幕", "", "Clockwork_Rush2", EnemyPat_Thunder_Grok },
    { "Sakana8", "雷をモチーフにした弾幕", "稲妻乱舞", "Clockwork_Rush2", EnemyPat_Thunder_Sakana },
    { "Claude8", "雷をモチーフにした弾幕", "", "Clockwork_Rush2", EnemyPat_Thunder_Claude },
    { "Qwen8", "雷をモチーフにした弾幕", "", "Clockwork_Rush2", EnemyPat_Thunder_Qwen },
    { "Vibe8", "雷をモチーフにした弾幕", "", "Clockwork_Rush2", EnemyPat_Thunder_Vibe },
    { "DeepSeek9", "吹雪をモチーフにした弾幕", "", "Whiteout_Loop", EnemyPat_Blizzard_DeepSeek },
    { "ChatGPT9", "吹雪をモチーフにした弾幕", "白銀風雪・ブリザードヴェール", "Whiteout_Loop", EnemyPat_Blizzard_ChatGPT },
    { "Gemini9", "吹雪をモチーフにした弾幕", "氷雪乱舞「ダイアモンドダスト」", "Whiteout_Loop", EnemyPat_Blizzard_Gemini },
    { "Grok9", "吹雪をモチーフにした弾幕", "", "Whiteout_Loop", EnemyPat_Blizzard_Grok },
    { "Sakana9", "吹雪をモチーフにした弾幕", "", "Whiteout_Loop", EnemyPat_Blizzard_Sakana },
    { "Claude9", "吹雪をモチーフにした弾幕", "", "Whiteout_Loop", EnemyPat_Blizzard_Claude },
    { "Qwen9", "吹雪をモチーフにした弾幕", "", "Whiteout_Loop", EnemyPat_Blizzard_Qwen },
    { "Vibe9", "吹雪をモチーフにした弾幕", "", "Whiteout_Loop", EnemyPat_Blizzard_Vibe },
    { "DeepSeek10", "竜をモチーフにした弾幕", "", "Dragonforge_Overture", EnemyPat_Dragon_DeepSeek },
    { "ChatGPT10", "竜をモチーフにした弾幕", "龍脈崩天（りゅうみゃくほうてん）", "Dragonforge_Overture", EnemyPat_Dragon_ChatGPT },
    { "Gemini10", "竜をモチーフにした弾幕", "", "Dragonforge_Overture", EnemyPat_Dragon_Gemini },
    { "Grok10", "竜をモチーフにした弾幕", "炎竜の息吹 ～ウネリの鱗～", "Dragonforge_Overture", EnemyPat_Dragon_Grok },
    { "Sakana10", "竜をモチーフにした弾幕", "", "Dragonforge_Overture", EnemyPat_Dragon_Sakana },
    { "Claude10", "竜をモチーフにした弾幕", "", "Dragonforge_Overture", EnemyPat_Dragon_Claude },
    { "Qwen10", "竜をモチーフにした弾幕", "", "Dragonforge_Overture", EnemyPat_Dragon_Qwen },
    { "Vibe10", "竜をモチーフにした弾幕", "", "Dragonforge_Overture", EnemyPat_Dragon_Vibe },
    { "DeepSeek11", "はかいこうせんをモチーフにした弾幕", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_DeepSeek },
    { "ChatGPT11", "はかいこうせんをモチーフにした弾幕", "終焉光線「はかいこうせん・アルティメットブレイク」", "Dragonforge_Overture2", EnemyPat_Hakaikousen_ChatGPT },
    { "Gemini11", "はかいこうせんをモチーフにした弾幕", "ハイパーチャージ・ブラスト", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Gemini },
    { "Grok11", "はかいこうせんをモチーフにした弾幕", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Grok },
    { "Sakana11", "はかいこうせんをモチーフにした弾幕", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Sakana },
    { "Claude11", "はかいこうせんをモチーフにした弾幕", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Claude },
    { "Qwen11", "はかいこうせんをモチーフにした弾幕", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Qwen },
    { "Vibe11", "はかいこうせんをモチーフにした弾幕", "", "Dragonforge_Overture2", EnemyPat_Hakaikousen_Vibe },
    { "DeepSeek12", "太陽をモチーフにした弾幕", "", "Scorching_Danmaku", EnemyPat_Sun_DeepSeek },
    { "ChatGPT12", "太陽をモチーフにした弾幕", "天照・紅炎輪廻（てんしょう・こうえんりんね）", "Scorching_Danmaku", EnemyPat_Sun_ChatGPT },
    { "Gemini12", "太陽をモチーフにした弾幕", "", "Scorching_Danmaku", EnemyPat_Sun_Gemini },
    { "Grok12", "太陽をモチーフにした弾幕", "", "Scorching_Danmaku", EnemyPat_Sun_Grok },
    { "Sakana12", "太陽をモチーフにした弾幕", "", "Scorching_Danmaku", EnemyPat_Sun_Sakana },
    { "Claude12", "太陽をモチーフにした弾幕", "", "Scorching_Danmaku", EnemyPat_Sun_Claude },
    { "Qwen12", "太陽をモチーフにした弾幕", "太陽のフレアとコロナ", "Scorching_Danmaku", EnemyPat_Sun_Qwen },
    { "Vibe12", "太陽をモチーフにした弾幕", "", "Scorching_Danmaku", EnemyPat_Sun_Vibe },
    { "DeepSeek13", "はっぱカッターをモチーフにした弾幕", "双葉嵐刃（ふたばらんじん）", "Sinnoh_Pulse", EnemyPat_RazorLeaf_DeepSeek },
    { "ChatGPT13", "はっぱカッターをモチーフにした弾幕", "翠嵐刃葉「リーフ・テンペスト」", "Sinnoh_Pulse", EnemyPat_RazorLeaf_ChatGPT },
    { "Gemini13", "はっぱカッターをモチーフにした弾幕", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Gemini },
    { "Grok13", "はっぱカッターをモチーフにした弾幕", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Grok },
    { "Sakana13", "はっぱカッターをモチーフにした弾幕", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Sakana },
    { "Claude13", "はっぱカッターをモチーフにした弾幕", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Claude },
    { "Qwen13", "はっぱカッターをモチーフにした弾幕", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Qwen },
    { "Vibe13", "はっぱカッターをモチーフにした弾幕", "", "Sinnoh_Pulse", EnemyPat_RazorLeaf_Vibe },
    { "DeepSeek14", "毒をモチーフにした弾幕", "", "Toxic_Clockwork", EnemyPat_Poison_DeepSeek },
    { "ChatGPT14", "毒をモチーフにした弾幕", "毒華散華（どくかさんげ）", "Toxic_Clockwork", EnemyPat_Poison_ChatGPT },
    { "Gemini14", "毒をモチーフにした弾幕", "", "Toxic_Clockwork", EnemyPat_Poison_Gemini },
    { "Grok14", "毒をモチーフにした弾幕", "", "Toxic_Clockwork", EnemyPat_Poison_Grok },
    { "Sakana14", "毒をモチーフにした弾幕", "", "Toxic_Clockwork", EnemyPat_Poison_Sakana },
    { "Claude14", "毒をモチーフにした弾幕", "毒華乱舞", "Toxic_Clockwork", EnemyPat_Poison_Claude },
    { "Qwen14", "毒をモチーフにした弾幕", "", "Toxic_Clockwork", EnemyPat_Poison_Qwen },
    { "Vibe14", "毒をモチーフにした弾幕", "", "Toxic_Clockwork", EnemyPat_Poison_Vibe },
    { "DeepSeek15", "洗濯機をモチーフにした弾幕", "", "Taiko_Lightning3", EnemyPat_WashingMachine_DeepSeek },
    { "ChatGPT15", "洗濯機をモチーフにした弾幕", "超高速洗浄「蒼流・脱水スピン」", "Taiko_Lightning3", EnemyPat_WashingMachine_ChatGPT },
    { "Gemini15", "洗濯機をモチーフにした弾幕", "回転水流と洗剤泡の全自動脱水弾幕", "Taiko_Lightning3", EnemyPat_WashingMachine_Gemini },
    { "Grok15", "洗濯機をモチーフにした弾幕", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Grok },
    { "Sakana15", "洗濯機をモチーフにした弾幕", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Sakana },
    { "Claude15", "洗濯機をモチーフにした弾幕", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Claude },
    { "Qwen15", "洗濯機をモチーフにした弾幕", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Qwen },
    { "Vibe15", "洗濯機をモチーフにした弾幕", "", "Taiko_Lightning3", EnemyPat_WashingMachine_Vibe },
    { "DeepSeek16", "囲碁をモチーフにした弾幕", "", "Bullet_Hell_Shrine", EnemyPat_Go_DeepSeek },
    { "ChatGPT16", "囲碁をモチーフにした弾幕", "黒白星羅（こくびゃくせいら） ～盤上に舞う無限の一手～", "Bullet_Hell_Shrine", EnemyPat_Go_ChatGPT },
    { "Gemini16", "囲碁をモチーフにした弾幕", "囲碁弾幕「布石と崩壊」", "Bullet_Hell_Shrine", EnemyPat_Go_Gemini },
    { "Grok16", "囲碁をモチーフにした弾幕", "", "Bullet_Hell_Shrine", EnemyPat_Go_Grok },
    { "Sakana16", "囲碁をモチーフにした弾幕", "", "Bullet_Hell_Shrine", EnemyPat_Go_Sakana },
    { "Claude16", "囲碁をモチーフにした弾幕", "", "Bullet_Hell_Shrine", EnemyPat_Go_Claude },
    { "Qwen16", "囲碁をモチーフにした弾幕", "", "Bullet_Hell_Shrine", EnemyPat_Go_Qwen },
    { "Vibe16", "囲碁をモチーフにした弾幕", "", "Bullet_Hell_Shrine", EnemyPat_Go_Vibe },
    { "DeepSeek17", "紅葉をモチーフにした弾幕", "", "Stormleaf_Skyshot", EnemyPat_Maple_DeepSeek },
    { "ChatGPT17", "紅葉をモチーフにした弾幕", "紅葉狩・秋風乱舞（もみじがり・あきかぜらんぶ）", "Stormleaf_Skyshot", EnemyPat_Maple_ChatGPT },
    { "Gemini17", "紅葉をモチーフにした弾幕", "紅葉の舞 ～ 舞い散る秋の疾風", "Stormleaf_Skyshot", EnemyPat_Maple_Gemini },
    { "Grok17", "紅葉をモチーフにした弾幕", "", "Stormleaf_Skyshot", EnemyPat_Maple_Grok },
    { "Sakana17", "紅葉をモチーフにした弾幕", "", "Stormleaf_Skyshot", EnemyPat_Maple_Sakana },
    { "Claude17", "紅葉をモチーフにした弾幕", "", "Stormleaf_Skyshot", EnemyPat_Maple_Claude },
    { "Qwen17", "紅葉をモチーフにした弾幕", "", "Stormleaf_Skyshot", EnemyPat_Maple_Qwen },
    { "Vibe17", "紅葉をモチーフにした弾幕", "", "Stormleaf_Skyshot", EnemyPat_Maple_Vibe },
    { "DeepSeek18", "クモの巣をモチーフにした弾幕", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_DeepSeek },
    { "ChatGPT18", "クモの巣をモチーフにした弾幕", "絡繰蜘蛛網「リサージュ・スパイダーウェブ」", "Toxic_Clockwork2", EnemyPat_SpiderWeb_ChatGPT },
    { "Gemini18", "クモの巣をモチーフにした弾幕", "捕食者の拘束陣 ～ Spider Web Trap", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Gemini },
    { "Grok18", "クモの巣をモチーフにした弾幕", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Grok },
    { "Sakana18", "クモの巣をモチーフにした弾幕", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Sakana },
    { "Claude18", "クモの巣をモチーフにした弾幕", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Claude },
    { "Qwen18", "クモの巣をモチーフにした弾幕", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Qwen },
    { "Vibe18", "クモの巣をモチーフにした弾幕", "", "Toxic_Clockwork2", EnemyPat_SpiderWeb_Vibe },
    { "DeepSeek19", "双曲線をモチーフにした弾幕", "", "Clockwork_Rush3", EnemyPat_Hyperbola_DeepSeek },
    { "ChatGPT19", "双曲線をモチーフにした弾幕", "双曲線・アポロニアンカタストロフィー", "Clockwork_Rush3", EnemyPat_Hyperbola_ChatGPT },
    { "Gemini19", "双曲線をモチーフにした弾幕", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Gemini },
    { "Grok19", "双曲線をモチーフにした弾幕", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Grok },
    { "Sakana19", "双曲線をモチーフにした弾幕", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Sakana },
    { "Claude19", "双曲線をモチーフにした弾幕", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Claude },
    { "Qwen19", "双曲線をモチーフにした弾幕", "双曲線符「ローテティング・ハイパーボラ」", "Clockwork_Rush3", EnemyPat_Hyperbola_Qwen },
    { "Vibe19", "双曲線をモチーフにした弾幕", "", "Clockwork_Rush3", EnemyPat_Hyperbola_Vibe },
    { "DeepSeek20", "砂時計をモチーフにした弾幕", "", "Youma", EnemyPat_Hourglass_DeepSeek },
    { "ChatGPT20", "砂時計をモチーフにした弾幕", "時刻砂界（じこくさかい）～クロノ・アワーグラス～", "Youma", EnemyPat_Hourglass_ChatGPT },
    { "Gemini20", "砂時計をモチーフにした弾幕", "時砂の回廊 - Chrono Hourglass", "Youma", EnemyPat_Hourglass_Gemini },
    { "Grok20", "砂時計をモチーフにした弾幕", "", "Youma", EnemyPat_Hourglass_Grok },
    { "Sakana20", "砂時計をモチーフにした弾幕", "", "Youma", EnemyPat_Hourglass_Sakana },
    { "Claude20", "砂時計をモチーフにした弾幕", "", "Youma", EnemyPat_Hourglass_Claude },
    { "Qwen20", "砂時計をモチーフにした弾幕", "", "Youma", EnemyPat_Hourglass_Qwen },
    { "Vibe20", "砂時計をモチーフにした弾幕", "", "Youma", EnemyPat_Hourglass_Vibe },
    { "DeepSeek21", "火山をモチーフにした弾幕", "", "Molten_Crown", EnemyPat_Volcano_DeepSeek },
    { "ChatGPT21", "火山をモチーフにした弾幕", "噴火「紅蓮昇華・灼熱の火山雨」", "Molten_Crown", EnemyPat_Volcano_ChatGPT },
    { "Gemini21", "火山をモチーフにした弾幕", "大噴火「マグマクライシス」", "Molten_Crown", EnemyPat_Volcano_Gemini },
    { "Grok21", "火山をモチーフにした弾幕", "", "Molten_Crown", EnemyPat_Volcano_Grok },
    { "Sakana21", "火山をモチーフにした弾幕", "", "Molten_Crown", EnemyPat_Volcano_Sakana },
    { "Claude21", "火山をモチーフにした弾幕", "", "Molten_Crown", EnemyPat_Volcano_Claude },
    { "Qwen21", "火山をモチーフにした弾幕", "", "Molten_Crown", EnemyPat_Volcano_Qwen },
    { "Vibe21", "火山をモチーフにした弾幕", "", "Molten_Crown", EnemyPat_Volcano_Vibe },
    { "DeepSeek22", "音ゲーをモチーフにした弾幕", "リズムノーツ・レイン", "Organ_Sprint", EnemyPat_RhythmGame_DeepSeek },
    { "ChatGPT22", "音ゲーをモチーフにした弾幕", "譜面奏弾「リズム・オブ・レイヴ」", "Organ_Sprint", EnemyPat_RhythmGame_ChatGPT },
    { "Gemini22", "音ゲーをモチーフにした弾幕", "", "Organ_Sprint", EnemyPat_RhythmGame_Gemini },
    { "Grok22", "音ゲーをモチーフにした弾幕", "", "Organ_Sprint", EnemyPat_RhythmGame_Grok },
    { "Sakana22", "音ゲーをモチーフにした弾幕", "", "Organ_Sprint", EnemyPat_RhythmGame_Sakana },
    { "Claude22", "音ゲーをモチーフにした弾幕", "", "Organ_Sprint", EnemyPat_RhythmGame_Claude },
    { "Qwen22", "音ゲーをモチーフにした弾幕", "", "Organ_Sprint", EnemyPat_RhythmGame_Qwen },
    { "Vibe22", "音ゲーをモチーフにした弾幕", "", "Organ_Sprint", EnemyPat_RhythmGame_Vibe },
    { "DeepSeek23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "Fractal_Boss", EnemyPat_Sierpinski_DeepSeek },
    { "ChatGPT23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "無限三角牢獄（インフィニット・トライアングル）", "Fractal_Boss", EnemyPat_Sierpinski_ChatGPT },
    { "Gemini23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "回転拡縮シェルピンスキーのギャスケット", "Fractal_Boss", EnemyPat_Sierpinski_Gemini },
    { "Grok23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "Fractal_Boss", EnemyPat_Sierpinski_Grok },
    { "Sakana23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "Fractal_Boss", EnemyPat_Sierpinski_Sakana },
    { "Claude23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "Fractal_Boss", EnemyPat_Sierpinski_Claude },
    { "Qwen23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "Fractal_Boss", EnemyPat_Sierpinski_Qwen },
    { "Vibe23", "シェルピンスキーのギャスケットをモチーフにした弾幕", "", "Fractal_Boss", EnemyPat_Sierpinski_Vibe },
    { "DeepSeek24", "メビウスの帯をモチーフにした弾幕", "メビウスのリボン", "Cosmic_Mobius", EnemyPat_Mobius_DeepSeek },
    { "ChatGPT24", "メビウスの帯をモチーフにした弾幕", "輪廻する虚無帯（メビウス・エターナル）", "Cosmic_Mobius", EnemyPat_Mobius_ChatGPT },
    { "Gemini24", "メビウスの帯をモチーフにした弾幕", "", "Cosmic_Mobius", EnemyPat_Mobius_Gemini },
    { "Grok24", "メビウスの帯をモチーフにした弾幕", "", "Cosmic_Mobius", EnemyPat_Mobius_Grok },
    { "Sakana24", "メビウスの帯をモチーフにした弾幕", "", "Cosmic_Mobius", EnemyPat_Mobius_Sakana },
    { "Claude24", "メビウスの帯をモチーフにした弾幕", "", "Cosmic_Mobius", EnemyPat_Mobius_Claude },
    { "Qwen24", "メビウスの帯をモチーフにした弾幕", "", "Cosmic_Mobius", EnemyPat_Mobius_Qwen },
    { "Vibe24", "メビウスの帯をモチーフにした弾幕", "", "Cosmic_Mobius", EnemyPat_Mobius_Vibe },
    { "DeepSeek25", "扇風機をモチーフにした弾幕", "", "Frantic_Pulse", EnemyPat_ElectricFan_DeepSeek },
    { "ChatGPT25", "扇風機をモチーフにした弾幕", "送風三連扇", "Frantic_Pulse", EnemyPat_ElectricFan_ChatGPT },
    { "Gemini25", "扇風機をモチーフにした弾幕", "", "Frantic_Pulse", EnemyPat_ElectricFan_Gemini },
    { "Grok25", "扇風機をモチーフにした弾幕", "", "Frantic_Pulse", EnemyPat_ElectricFan_Grok },
    { "Sakana25", "扇風機をモチーフにした弾幕", "", "Frantic_Pulse", EnemyPat_ElectricFan_Sakana },
    { "Claude25", "扇風機をモチーフにした弾幕", "", "Frantic_Pulse", EnemyPat_ElectricFan_Claude },
    { "Qwen25", "扇風機をモチーフにした弾幕", "", "Frantic_Pulse", EnemyPat_ElectricFan_Qwen },
    { "Vibe25", "扇風機をモチーフにした弾幕", "", "Frantic_Pulse", EnemyPat_ElectricFan_Vibe },
    { "DeepSeek26", "文字を活用した弾幕", "", "Shamisen_Run", EnemyPat_Moji_DeepSeek },
    { "ChatGPT26", "文字を活用した弾幕", "筆文字弾幕", "Shamisen_Run", EnemyPat_Moji_ChatGPT },
    { "Gemini26", "文字を活用した弾幕", "", "Shamisen_Run", EnemyPat_Moji_Gemini },
    { "Grok26", "文字を活用した弾幕", "", "Shamisen_Run", EnemyPat_Moji_Grok },
    { "Sakana26", "文字を活用した弾幕", "弾・再集結", "Shamisen_Run", EnemyPat_Moji_Sakana },
    { "Claude26", "文字を活用した弾幕", "", "Shamisen_Run", EnemyPat_Moji_Claude },
    { "Qwen26", "文字を活用した弾幕", "", "Shamisen_Run", EnemyPat_Moji_Qwen },
    { "Vibe26", "文字を活用した弾幕", "", "Shamisen_Run", EnemyPat_Moji_Vibe },
    { "DeepSeek27", "手裏剣をモチーフにした弾幕", "", "Gongline_Riot", EnemyPat_Shuriken_DeepSeek },
    { "ChatGPT27", "手裏剣をモチーフにした弾幕", "旋風手裏剣「散華の陣」", "Gongline_Riot", EnemyPat_Shuriken_ChatGPT },
    { "Gemini27", "手裏剣をモチーフにした弾幕", "旋風・影分身十字", "Gongline_Riot", EnemyPat_Shuriken_Gemini },
    { "Grok27", "手裏剣をモチーフにした弾幕", "", "Gongline_Riot", EnemyPat_Shuriken_Grok },
    { "Sakana27", "手裏剣をモチーフにした弾幕", "", "Gongline_Riot", EnemyPat_Shuriken_Sakana },
    { "Claude27", "手裏剣をモチーフにした弾幕", "", "Gongline_Riot", EnemyPat_Shuriken_Claude },
    { "Qwen27", "手裏剣をモチーフにした弾幕", "", "Gongline_Riot", EnemyPat_Shuriken_Qwen },
    { "Vibe27", "手裏剣をモチーフにした弾幕", "", "Gongline_Riot", EnemyPat_Shuriken_Vibe },
    { "DeepSeek28", "金閣寺の一枚天井", "", "Gongline_Riot2", EnemyPat_Kinkakuji_DeepSeek },
    { "ChatGPT28", "金閣寺の一枚天井", "新難題「金閣楼の落天回廊」", "Gongline_Riot2", EnemyPat_Kinkakuji_ChatGPT },
    { "Gemini28", "金閣寺の一枚天井", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Gemini },
    { "Grok28", "金閣寺の一枚天井", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Grok },
    { "Sakana28", "金閣寺の一枚天井", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Sakana },
    { "Claude28", "金閣寺の一枚天井", "絢爛「煌金の板と旋弾の底」", "Gongline_Riot2", EnemyPat_Kinkakuji_Claude },
    { "Qwen28", "金閣寺の一枚天井", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Qwen },
    { "Vibe28", "金閣寺の一枚天井", "", "Gongline_Riot2", EnemyPat_Kinkakuji_Vibe },
    { "DeepSeek29", "シャボン玉をモチーフにした弾幕", "", "Bubble_Horizon", EnemyPat_SoapBubbles_DeepSeek },
    { "ChatGPT29", "シャボン玉をモチーフにした弾幕", "泡沫「虹色泡沫庭園（バブル・ガーデン）」", "Bubble_Horizon", EnemyPat_SoapBubbles_ChatGPT },
    { "Gemini29", "シャボン玉をモチーフにした弾幕", "ソープバブル・トラップ", "Bubble_Horizon", EnemyPat_SoapBubbles_Gemini },
    { "Grok29", "シャボン玉をモチーフにした弾幕", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Grok },
    { "Sakana29", "シャボン玉をモチーフにした弾幕", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Sakana },
    { "Claude29", "シャボン玉をモチーフにした弾幕", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Claude },
    { "Qwen29", "シャボン玉をモチーフにした弾幕", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Qwen },
    { "Vibe29", "シャボン玉をモチーフにした弾幕", "", "Bubble_Horizon", EnemyPat_SoapBubbles_Vibe },
    { "DeepSeek30", "ショットガンをモチーフにした弾幕", "", "Torque_Anthem", EnemyPat_Shotgun_DeepSeek },
    { "ChatGPT30", "ショットガンをモチーフにした弾幕", "散弾爆裂「ラピッド・バレル」", "Torque_Anthem", EnemyPat_Shotgun_ChatGPT },
    { "Gemini30", "ショットガンをモチーフにした弾幕", "クロースレンジ・バースト（近接信管の散弾）", "Torque_Anthem", EnemyPat_Shotgun_Gemini },
    { "Grok30", "ショットガンをモチーフにした弾幕", "", "Torque_Anthem", EnemyPat_Shotgun_Grok },
    { "Sakana30", "ショットガンをモチーフにした弾幕", "", "Torque_Anthem", EnemyPat_Shotgun_Sakana },
    { "Claude30", "ショットガンをモチーフにした弾幕", "", "Torque_Anthem", EnemyPat_Shotgun_Claude },
    { "Qwen30", "ショットガンをモチーフにした弾幕", "", "Torque_Anthem", EnemyPat_Shotgun_Qwen },
    { "Kimi30", "ショットガンをモチーフにした弾幕", "", "Torque_Anthem", EnemyPat_Shotgun_Kimi },
    { "DeepSeek31", "戻り弾幕", "", "Youma2", EnemyPat_Reverse_DeepSeek },
    { "ChatGPT31", "戻り弾幕", "輪廻帰弾「ブーメラン・エクリプス」", "Youma2", EnemyPat_Reverse_ChatGPT },
    { "Gemini31", "戻り弾幕", "", "Youma2", EnemyPat_Reverse_Gemini },
    { "Grok31", "戻り弾幕", "", "Youma2", EnemyPat_Reverse_Grok },
    { "Sakana31", "戻り弾幕", "", "Youma2", EnemyPat_Reverse_Sakana },
    { "Claude31", "戻り弾幕", "", "Youma2", EnemyPat_Reverse_Claude },
    { "Qwen31", "戻り弾幕", "", "Youma2", EnemyPat_Reverse_Qwen },
    { "Kimi31", "戻り弾幕", "還り道（かえりみち）", "Youma2", EnemyPat_Reverse_Kimi },
    { "DeepSeek32", "ボンバーマンをモチーフにした弾幕", "", "Pixel_Victory_Run", EnemyPat_Bomberman_DeepSeek },
    { "ChatGPT32", "ボンバーマンをモチーフにした弾幕", "爆炎迷宮「ボム・パニック・クロス」", "Pixel_Victory_Run", EnemyPat_Bomberman_ChatGPT },
    { "Gemini32", "ボンバーマンをモチーフにした弾幕", "ディレイド・クロス・ボンバー", "Pixel_Victory_Run", EnemyPat_Bomberman_Gemini },
    { "Grok32", "ボンバーマンをモチーフにした弾幕", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Grok },
    { "Sakana32", "ボンバーマンをモチーフにした弾幕", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Sakana },
    { "Claude32", "ボンバーマンをモチーフにした弾幕", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Claude },
    { "Qwen32", "ボンバーマンをモチーフにした弾幕", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Qwen },
    { "Kimi32", "ボンバーマンをモチーフにした弾幕", "", "Pixel_Victory_Run", EnemyPat_Bomberman_Kimi },
    { "DeepSeek33", "回避不可能な弾幕", "", "Torpedo_Hymn", EnemyPat_Unavoidable_DeepSeek },
    { "ChatGPT33", "回避不可能な弾幕", "", "Torpedo_Hymn", EnemyPat_Unavoidable_ChatGPT },
    { "Gemini33", "回避不可能な弾幕", "", "Torpedo_Hymn", EnemyPat_Unavoidable_Gemini },
    { "Grok33", "回避不可能な弾幕", "", "Torpedo_Hymn", EnemyPat_Unavoidable_Grok },
    { "Sakana33", "回避不可能な弾幕", "", "Torpedo_Hymn", EnemyPat_Unavoidable_Sakana },
    { "Claude33", "回避不可能な弾幕", "絶対回避不可能", "Torpedo_Hymn", EnemyPat_Unavoidable_Claude },
    { "Qwen33", "回避不可能な弾幕", "", "Torpedo_Hymn", EnemyPat_Unavoidable_Qwen },
    { "Kimi33", "回避不可能な弾幕", "", "Torpedo_Hymn", EnemyPat_Unavoidable_Kimi },
    { "DeepSeek34", "マッチをモチーフにした弾幕", "", "Kagura_Storm", EnemyPat_Match_DeepSeek },
    { "ChatGPT34", "マッチをモチーフにした弾幕", "擦火点（さっかてん）", "Kagura_Storm", EnemyPat_Match_ChatGPT },
    { "Gemini34", "マッチをモチーフにした弾幕", "", "Kagura_Storm", EnemyPat_Match_Gemini },
    { "Grok34", "マッチをモチーフにした弾幕", "", "Kagura_Storm", EnemyPat_Match_Grok },
    { "Sakana34", "マッチをモチーフにした弾幕", "", "Kagura_Storm", EnemyPat_Match_Sakana },
    { "Claude34", "マッチをモチーフにした弾幕", "", "Kagura_Storm", EnemyPat_Match_Claude },
    { "Qwen34", "マッチをモチーフにした弾幕", "", "Kagura_Storm", EnemyPat_Match_Qwen },
    { "Kimi34", "マッチをモチーフにした弾幕", "", "Kagura_Storm", EnemyPat_Match_Kimi },
    { "DeepSeek35", "ワインダーを活用した弾幕", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_DeepSeek },
    { "ChatGPT35", "ワインダーを活用した弾幕", "蛇腹双螺旋（ジャバラ・ツインスパイラル）", "Spellbound_Bamboo_Rush", EnemyPat_Winder_ChatGPT },
    { "Gemini35", "ワインダーを活用した弾幕", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Gemini },
    { "Grok35", "ワインダーを活用した弾幕", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Grok },
    { "Sakana35", "ワインダーを活用した弾幕", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Sakana },
    { "Claude35", "ワインダーを活用した弾幕", "渦墨(うずずみ)", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Claude },
    { "Qwen35", "ワインダーを活用した弾幕", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Qwen },
    { "Kimi35", "ワインダーを活用した弾幕", "", "Spellbound_Bamboo_Rush", EnemyPat_Winder_Kimi },
    { "DeepSeek36", "ポップコーンをモチーフにした弾幕", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_DeepSeek },
    { "ChatGPT36", "ポップコーンをモチーフにした弾幕", "爆ぜる黄金粒 - ポップコーン・カーニバル", "Pixel_Pop_Panic", EnemyPat_Popcorn_ChatGPT },
    { "Gemini36", "ポップコーンをモチーフにした弾幕", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Gemini },
    { "Grok36", "ポップコーンをモチーフにした弾幕", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Grok },
    { "Sakana36", "ポップコーンをモチーフにした弾幕", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Sakana },
    { "Claude36", "ポップコーンをモチーフにした弾幕", "爆ぜる粒、跳ねる音 ― ポップコーン・ケトル", "Pixel_Pop_Panic", EnemyPat_Popcorn_Claude },
    { "Qwen36", "ポップコーンをモチーフにした弾幕", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Qwen },
    { "Kimi36", "ポップコーンをモチーフにした弾幕", "", "Pixel_Pop_Panic", EnemyPat_Popcorn_Kimi },
    { "DeepSeek37", "立体的に見える弾幕", "", "Sphere_Breaker", EnemyPat_3D_DeepSeek },
    { "ChatGPT37", "立体的に見える弾幕", "螺旋虚洞「アビス・スパイラル・コリドー」", "Sphere_Breaker", EnemyPat_3D_ChatGPT },
    { "Gemini37", "立体的に見える弾幕", "", "Sphere_Breaker", EnemyPat_3D_Gemini },
    { "Grok37", "立体的に見える弾幕", "", "Sphere_Breaker", EnemyPat_3D_Grok },
    { "Sakana37", "立体的に見える弾幕", "", "Sphere_Breaker", EnemyPat_3D_Sakana },
    { "Claude37", "立体的に見える弾幕", "深宵環（しんしょうかん）", "Sphere_Breaker", EnemyPat_3D_Claude },
    { "Qwen37", "立体的に見える弾幕", "", "Sphere_Breaker", EnemyPat_3D_Qwen },
    { "Kimi37", "立体的に見える弾幕", "", "Sphere_Breaker", EnemyPat_3D_Kimi },
    { "DeepSeek38", "レーザーを活用した弾幕", "", "Cage_Of_Lasers", EnemyPat_Laser_DeepSeek },
    { "ChatGPT38", "レーザーを活用した弾幕", "機械仕掛けの光織陣（レーザー・ルーム）", "Cage_Of_Lasers", EnemyPat_Laser_ChatGPT },
    { "Gemini38", "レーザーを活用した弾幕", "カッティング・ケージ（裁断される檻）", "Cage_Of_Lasers", EnemyPat_Laser_Gemini },
    { "Grok38", "レーザーを活用した弾幕", "", "Cage_Of_Lasers", EnemyPat_Laser_Grok },
    { "Sakana38", "レーザーを活用した弾幕", "", "Cage_Of_Lasers", EnemyPat_Laser_Sakana },
    { "Claude38", "レーザーを活用した弾幕", "", "Cage_Of_Lasers", EnemyPat_Laser_Claude },
    { "Qwen38", "レーザーを活用した弾幕", "", "Cage_Of_Lasers", EnemyPat_Laser_Qwen },
    { "Kimi38", "レーザーを活用した弾幕", "", "Cage_Of_Lasers", EnemyPat_Laser_Kimi },
    { "DeepSeek39", "インベーダーゲームをモチーフにした弾幕", "", "Quiet_Opening", EnemyPat_Invader_DeepSeek },
    { "ChatGPT39", "インベーダーゲームをモチーフにした弾幕", "侵略編隊『ドットファランクス』", "Quiet_Opening", EnemyPat_Invader_ChatGPT },
    { "Gemini39", "インベーダーゲームをモチーフにした弾幕", "", "Quiet_Opening", EnemyPat_Invader_Gemini },
    { "Grok39", "インベーダーゲームをモチーフにした弾幕", "", "Quiet_Opening", EnemyPat_Invader_Grok },
    { "Sakana39", "インベーダーゲームをモチーフにした弾幕", "", "Quiet_Opening", EnemyPat_Invader_Sakana },
    { "Claude39", "インベーダーゲームをモチーフにした弾幕", "", "Quiet_Opening", EnemyPat_Invader_Claude },
    { "Qwen39", "インベーダーゲームをモチーフにした弾幕", "", "Quiet_Opening", EnemyPat_Invader_Qwen },
    { "Kimi39", "インベーダーゲームをモチーフにした弾幕", "", "Quiet_Opening", EnemyPat_Invader_Kimi },
    { "DeepSeek40", "二重振り子をモチーフにした弾幕", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_DeepSeek },
    { "ChatGPT40", "二重振り子をモチーフにした弾幕", "双鎖振動「カオス・ペンデュラム」", "Pendulum_Chaos", EnemyPat_DoublePendulum_ChatGPT },
    { "Gemini40", "二重振り子をモチーフにした弾幕", "カオス・ペンデュラム", "Pendulum_Chaos", EnemyPat_DoublePendulum_Gemini },
    { "Grok40", "二重振り子をモチーフにした弾幕", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Grok },
    { "Sakana40", "二重振り子をモチーフにした弾幕", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Sakana },
    { "Claude40", "二重振り子をモチーフにした弾幕", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Claude },
    { "Qwen40", "二重振り子をモチーフにした弾幕", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Qwen },
    { "Kimi40", "二重振り子をモチーフにした弾幕", "", "Pendulum_Chaos", EnemyPat_DoublePendulum_Kimi },
    { "DeepSeek41", "ブロック崩しをモチーフにした弾幕", "バウンド・カタストロフ", "Quiet_Opening2", EnemyPat_BlockBreak_DeepSeek },
    { "ChatGPT41", "ブロック崩しをモチーフにした弾幕", "ブロック崩壊領域 - リバウンド・カタストロフィ", "Quiet_Opening2", EnemyPat_BlockBreak_ChatGPT },
    { "Gemini41", "ブロック崩しをモチーフにした弾幕", "", "Quiet_Opening2", EnemyPat_BlockBreak_Gemini },
    { "Grok41", "ブロック崩しをモチーフにした弾幕", "", "Quiet_Opening2", EnemyPat_BlockBreak_Grok },
    { "Sakana41", "ブロック崩しをモチーフにした弾幕", "", "Quiet_Opening2", EnemyPat_BlockBreak_Sakana },
    { "Claude41", "ブロック崩しをモチーフにした弾幕", "", "Quiet_Opening2", EnemyPat_BlockBreak_Claude },
    { "Qwen41", "ブロック崩しをモチーフにした弾幕", "", "Quiet_Opening2", EnemyPat_BlockBreak_Qwen },
    { "Kimi41", "ブロック崩しをモチーフにした弾幕", "", "Quiet_Opening2", EnemyPat_BlockBreak_Kimi },
    { "DeepSeek42", "ピラミッドをモチーフにした弾幕", "", "Desert_Storm", EnemyPat_Pyramid_DeepSeek },
    { "ChatGPT42", "ピラミッドをモチーフにした弾幕", "王墓崩壊 ― ピラミッド・カタストロフ", "Desert_Storm", EnemyPat_Pyramid_ChatGPT },
    { "Gemini42", "ピラミッドをモチーフにした弾幕", "ファラオ・コア：黄金の階層構築", "Desert_Storm", EnemyPat_Pyramid_Gemini },
    { "Grok42", "ピラミッドをモチーフにした弾幕", "", "Desert_Storm", EnemyPat_Pyramid_Grok },
    { "Claude42", "ピラミッドをモチーフにした弾幕", "", "Desert_Storm", EnemyPat_Pyramid_Claude },
    { "Qwen42", "ピラミッドをモチーフにした弾幕", "", "Desert_Storm", EnemyPat_Pyramid_Qwen },
    { "Kimi42", "ピラミッドをモチーフにした弾幕", "", "Desert_Storm", EnemyPat_Pyramid_Kimi },
    { "Zai42", "ピラミッドをモチーフにした弾幕", "", "Desert_Storm", EnemyPat_Pyramid_Zai },
    { "DeepSeek43", "ボスが体当たりしてくる弾幕", "", "Cathedral_Ashes", EnemyPat_Tackle_DeepSeek },
    { "ChatGPT43", "ボスが体当たりしてくる弾幕", "獣王突撃・轟雷狩猟陣", "Cathedral_Ashes", EnemyPat_Tackle_ChatGPT },
    { "Gemini43", "ボスが体当たりしてくる弾幕", "", "Cathedral_Ashes", EnemyPat_Tackle_Gemini },
    { "Grok43", "ボスが体当たりしてくる弾幕", "", "Cathedral_Ashes", EnemyPat_Tackle_Grok },
    { "Claude43", "ボスが体当たりしてくる弾幕", "", "Cathedral_Ashes", EnemyPat_Tackle_Claude },
    { "Qwen43", "ボスが体当たりしてくる弾幕", "", "Cathedral_Ashes", EnemyPat_Tackle_Qwen },
    { "Kimi43", "ボスが体当たりしてくる弾幕", "", "Cathedral_Ashes", EnemyPat_Tackle_Kimi },
    { "Zai43", "ボスが体当たりしてくる弾幕", "グラビティ・コメット・レムナント", "Cathedral_Ashes", EnemyPat_Tackle_Zai },
    { "DeepSeek44", "矢印をモチーフにした弾幕", "鏃穿つ方陣", "Arrow_Circuit", EnemyPat_Arrow_DeepSeek },
    { "ChatGPT44", "矢印をモチーフにした弾幕", "矢印機関「アロー・コンベア」", "Arrow_Circuit", EnemyPat_Arrow_ChatGPT },
    { "Gemini44", "矢印をモチーフにした弾幕", "", "Arrow_Circuit", EnemyPat_Arrow_Gemini },
    { "Grok44", "矢印をモチーフにした弾幕", "", "Arrow_Circuit", EnemyPat_Arrow_Grok },
    { "Claude44", "矢印をモチーフにした弾幕", "", "Arrow_Circuit", EnemyPat_Arrow_Claude },
    { "Qwen44", "矢印をモチーフにした弾幕", "", "Arrow_Circuit", EnemyPat_Arrow_Qwen },
    { "Kimi44", "矢印をモチーフにした弾幕", "", "Arrow_Circuit", EnemyPat_Arrow_Kimi },
    { "Zai44", "矢印をモチーフにした弾幕", "ホーミング・イリュージョン", "Arrow_Circuit", EnemyPat_Arrow_Zai },
    { "DeepSeek45", "DNAをモチーフにした弾幕", "", "Helix_Test_Tube", EnemyPat_DNA_DeepSeek },
    { "ChatGPT45", "DNAをモチーフにした弾幕", "螺旋遺伝子「ダブルヘリックス・レプリケーション」", "Helix_Test_Tube", EnemyPat_DNA_ChatGPT },
    { "Gemini45", "DNAをモチーフにした弾幕", "", "Helix_Test_Tube", EnemyPat_DNA_Gemini },
    { "Grok45", "DNAをモチーフにした弾幕", "", "Helix_Test_Tube", EnemyPat_DNA_Grok },
    { "Claude45", "DNAをモチーフにした弾幕", "", "Helix_Test_Tube", EnemyPat_DNA_Claude },
    { "Qwen45", "DNAをモチーフにした弾幕", "", "Helix_Test_Tube", EnemyPat_DNA_Qwen },
    { "Kimi45", "DNAをモチーフにした弾幕", "ヘリカル・ゲノム", "Crystalline Rain Circuit", EnemyPat_DNA_Kimi },
    { "Zai45", "DNAをモチーフにした弾幕", "", "Helix_Test_Tube", EnemyPat_DNA_Zai },
    { "DeepSeek46", "大砂嵐をモチーフにした弾幕", "砂塵旋風『埋没の大砂丘』", "Desert Mirage Run", EnemyPat_SandStorm_DeepSeek },
    { "ChatGPT46", "大砂嵐をモチーフにした弾幕", "砂塵眼・テンペストコア", "Neon_Dune_Rush", EnemyPat_SandStorm_ChatGPT },
    { "Gemini46", "大砂嵐をモチーフにした弾幕", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Gemini },
    { "Grok46", "大砂嵐をモチーフにした弾幕", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Grok },
    { "Claude46", "大砂嵐をモチーフにした弾幕", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Claude },
    { "Qwen46", "大砂嵐をモチーフにした弾幕", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Qwen },
    { "Kimi46", "大砂嵐をモチーフにした弾幕", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Kimi },
    { "Zai46", "大砂嵐をモチーフにした弾幕", "", "Neon_Dune_Rush", EnemyPat_SandStorm_Zai },
    { "DeepSeek47", "へにょりレーザーを用いた弾幕", "蛇腹追詰レーザー “メアンダサーペント”", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_DeepSeek },
    { "ChatGPT47", "へにょりレーザーを用いた弾幕", "蛇の巣（Serpent Nest）", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_ChatGPT },
    { "Gemini47", "へにょりレーザーを用いた弾幕", "へにょりスラローム（曲折迷宮）", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Gemini },
    { "Grok47", "へにょりレーザーを用いた弾幕", "蛇舞繚乱（へびまいりょうらん）", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Grok },
    { "Claude47", "へにょりレーザーを用いた弾幕", "大蛇乱舞(おろちらんぶ)", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Claude },
    { "Qwen47", "へにょりレーザーを用いた弾幕", "", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Qwen },
    { "Kimi47", "へにょりレーザーを用いた弾幕", "螺旋の縫い目（Spiral Seam）", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Kimi },
    { "Zai47", "へにょりレーザーを用いた弾幕", "蠕動交差（ぜんどうこうさ）の檻", "Ryukyu Neon Rush", EnemyPat_HenyoriLaser_Zai },
    { "DeepSeek48", "潮吹きをモチーフにした弾幕", "天恵の噴泉（ブレス・オブ・セタシア）", "Tidal Ascend", EnemyPat_Spout_DeepSeek },
    { "ChatGPT48", "潮吹きをモチーフにした弾幕", "潮吹き「ブロウ・カラム」", "Tidal Ascend", EnemyPat_Spout_ChatGPT },
    { "Gemini48", "潮吹きをモチーフにした弾幕", "大噴流「アクア・プレッシャー」", "Tidal Ascend", EnemyPat_Spout_Gemini },
    { "Grok48", "潮吹きをモチーフにした弾幕", "激潮噴出（Geki-chou Funshutsu）", "Tidal Ascend", EnemyPat_Spout_Grok },
    { "Claude48", "潮吹きをモチーフにした弾幕", "怒濤潮吹き", "Tidal Ascend", EnemyPat_Spout_Claude },
    { "Qwen48", "潮吹きをモチーフにした弾幕", "", "Tidal Ascend", EnemyPat_Spout_Qwen },
    { "Sakana48", "潮吹きをモチーフにした弾幕", "潮吹き噴流（しおふきふんりゅう）", "Tidal Ascend", EnemyPat_Spout_Sakana },
    { "Zai48", "潮吹きをモチーフにした弾幕", "", "Tidal Ascend", EnemyPat_Spout_Zai },
    { "DeepSeek49", "ライフゲームをモチーフにした弾幕", "コンウェイの産声（グライダーガン変奏）", "Digital Grid Run", EnemyPat_LifeGame_DeepSeek },
    { "ChatGPT49", "ライフゲームをモチーフにした弾幕", "コンウェイ・コロニー", "Digital Grid Run", EnemyPat_LifeGame_ChatGPT },
    { "Gemini49", "ライフゲームをモチーフにした弾幕", "ジェネレーション・グリッド（Generation Grid）", "Digital Grid Run", EnemyPat_LifeGame_Gemini },
    { "Grok49", "ライフゲームをモチーフにした弾幕", "生命の脈動 (Pulsating Life)", "Digital Grid Run", EnemyPat_LifeGame_Grok },
    { "Claude49", "ライフゲームをモチーフにした弾幕", "生々流転", "Digital Grid Run", EnemyPat_LifeGame_Claude },
    { "Qwen49", "ライフゲームをモチーフにした弾幕", "", "Digital Grid Run", EnemyPat_LifeGame_Qwen },
    { "Kimi49", "ライフゲームをモチーフにした弾幕", "世代交代の連鎖（Generational Chain）", "Digital Grid Run", EnemyPat_LifeGame_Kimi },
    { "Zai49", "ライフゲームをモチーフにした弾幕", "細胞律動弾幕 -R-pentomino-", "Digital Grid Run", EnemyPat_LifeGame_Zai },
    { "DeepSeek50", "スイミーをモチーフにした弾幕", "大きな魚の目になるスイミー", "Shoal Storm Run", EnemyPat_Swimmy_DeepSeek },
    { "ChatGPT50", "スイミーをモチーフにした弾幕", "スイミー（群れの目）", "Shoal Storm Run", EnemyPat_Swimmy_ChatGPT },
    { "Gemini50", "スイミーをモチーフにした弾幕", "スイミー・フォーメーション（Swimmy Tactics）", "Shoal Storm Run", EnemyPat_Swimmy_Gemini },
    { "Grok50", "スイミーをモチーフにした弾幕", "スイミーの大群形成（Swimmy's School Formation）", "Shoal Storm Run", EnemyPat_Swimmy_Grok },
    { "Claude50", "スイミーをモチーフにした弾幕", "群魚結像 -スイミー-", "Shoal Storm Run", EnemyPat_Swimmy_Claude },
    { "Qwen50", "スイミーをモチーフにした弾幕", "", "Shoal Storm Run", EnemyPat_Swimmy_Qwen },
    { "Kimi50", "スイミーをモチーフにした弾幕", "スイミーの大魚陣形", "Shoal Storm Run", EnemyPat_Swimmy_Kimi },
    { "Zai50", "スイミーをモチーフにした弾幕", "紅き群れと一匹の墨～巨大魚の遊泳～", "Shoal Storm Run", EnemyPat_Swimmy_Zai },
    { "DeepSeek51", "イライラ棒をモチーフにした弾幕", "電網迷路「フラッシュ・メイズ」", "Clockwork Panic Run", EnemyPat_Irairabou_DeepSeek },
    { "ChatGPT51", "イライラ棒をモチーフにした弾幕", "イライラ迷路", "Clockwork Panic Run", EnemyPat_Irairabou_ChatGPT },
    { "Gemini51", "イライラ棒をモチーフにした弾幕", "電撃精密回廊 ～ イライラ・コリドー", "Clockwork Panic Run", EnemyPat_Irairabou_Gemini },
    { "Grok51", "イライラ棒をモチーフにした弾幕", "イライラ棒・極（きわみ）", "Clockwork Panic Run", EnemyPat_Irairabou_Grok },
    { "Claude51", "イライラ棒をモチーフにした弾幕", "銅線回廊", "Clockwork Panic Run", EnemyPat_Irairabou_Claude },
    { "Qwen51", "イライラ棒をモチーフにした弾幕", "電流迷路『イライラ・コイル』", "Clockwork Panic Run", EnemyPat_Irairabou_Qwen },
    { "Kimi51", "イライラ棒をモチーフにした弾幕", "電壁「ビリビリ回廊」", "Clockwork Panic Run", EnemyPat_Irairabou_Kimi },
    { "Zai51", "イライラ棒をモチーフにした弾幕", "", "Clockwork Panic Run", EnemyPat_Irairabou_Zai },
    { "DeepSeek52", "蜂をモチーフにした弾幕", "蜂の八字舞踏「蜜導の輪舞」", "Hive Storm", EnemyPat_Bee_DeepSeek },
    { "ChatGPT52", "蜂をモチーフにした弾幕", "ハニカム・スウォーム（Honeycomb Swarm）", "Hive Storm", EnemyPat_Bee_ChatGPT },
    { "Gemini52", "蜂をモチーフにした弾幕", "ハニカム・プリズン ＆ デス・ニードル（蜜蜂の檻と死の針）", "Hive Storm", EnemyPat_Bee_Gemini },
    { "Grok52", "蜂をモチーフにした弾幕", "蜂の巣攻勢 - Honeycomb Swarm", "Hive Storm", EnemyPat_Bee_Grok },
    { "Claude52", "蜂をモチーフにした弾幕", "羽音の八の字舞", "Hive Storm", EnemyPat_Bee_Claude },
    { "Qwen52", "蜂をモチーフにした弾幕", "", "Hive Storm", EnemyPat_Bee_Qwen },
    { "Kimi52", "蜂をモチーフにした弾幕", "蜜蝋六重奏（ハニカム・セクテット）", "Hive Storm", EnemyPat_Bee_Kimi },
    { "Zai52", "蜂をモチーフにした弾幕", "六角の檻と狂気の羽音", "Hive Storm", EnemyPat_Bee_Zai },
    { "DeepSeek53", "大文字をモチーフにした弾幕", "鋭角の審判「エイペックス・ジャッジメント」", "Taiko Skyline Run", EnemyPat_Daimonji_DeepSeek },
    { "ChatGPT53", "大文字をモチーフにした弾幕", "SHIFT FALL（大文字の雨）", "Taiko Skyline Run", EnemyPat_Daimonji_ChatGPT },
    { "Gemini53", "大文字をモチーフにした弾幕", "焔符「大文字送り火 -篝火の檻-」", "Taiko Skyline Run", EnemyPat_Daimonji_Gemini },
    { "Grok53", "大文字をモチーフにした弾幕", "Capital A - Descent Frame", "Taiko Skyline Run", EnemyPat_Daimonji_Grok },
    { "Claude53", "大文字をモチーフにした弾幕", "大文字送り火", "Taiko Skyline Run", EnemyPat_Daimonji_Claude },
    { "Qwen53", "大文字をモチーフにした弾幕", "", "Taiko Skyline Run", EnemyPat_Daimonji_Qwen },
    { "Kimi53", "大文字をモチーフにした弾幕", "Absolute Apex", "Taiko Skyline Run", EnemyPat_Daimonji_Kimi },
    { "Zai53", "大文字をモチーフにした弾幕", "「Z」字斬撃弾幕", "Taiko Skyline Run", EnemyPat_Daimonji_Zai },
    { "DeepSeek54", "ビールかけをモチーフにした弾幕", "祝勝の泡濁流", "Tipsy Brass Parade", EnemyPat_BeerSpray_DeepSeek },
    { "ChatGPT54", "ビールかけをモチーフにした弾幕", "ビールかけ", "Tipsy Brass Parade", EnemyPat_BeerSpray_ChatGPT },
    { "Gemini54", "ビールかけをモチーフにした弾幕", "歓喜のビア・シャワー（Cheers! Burst）", "Tipsy Brass Parade", EnemyPat_BeerSpray_Gemini },
    { "Grok54", "ビールかけをモチーフにした弾幕", "無限ビールかけ祭り（Endless Beer Shower）", "Tipsy Brass Parade", EnemyPat_BeerSpray_Grok },
    { "Claude54", "ビールかけをモチーフにした弾幕", "祝勝ビールかけ", "Tipsy Brass Parade", EnemyPat_BeerSpray_Claude },
    { "Qwen54", "ビールかけをモチーフにした弾幕", "", "Tipsy Brass Parade", EnemyPat_BeerSpray_Qwen },
    { "Kimi54", "ビールかけをモチーフにした弾幕", "泡沫の宴（エビュリエンス・フェスト）", "Tipsy Brass Parade", EnemyPat_BeerSpray_Kimi },
    { "Zai54", "ビールかけをモチーフにした弾幕", "溢れる狂乱の飛沫（エクスプロージング・ビアスプラッシュ）", "Tipsy Brass Parade", EnemyPat_BeerSpray_Zai },
    { "DeepSeek55", "サムネ映えする弾幕", "時空の歪曲円舞《クロノス・スパイラル》", "Astral Blade Run", EnemyPat_ThumbnailFriendly_DeepSeek },
    { "ChatGPT55", "サムネ映えする弾幕", "ガラス細工の万華鏡", "Astral Blade Run", EnemyPat_ThumbnailFriendly_ChatGPT },
    { "Gemini55", "サムネ映えする弾幕", "カレイド・フェニックス（万華鏡の不死鳥）", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Gemini },
    { "Grok55", "サムネ映えする弾幕", "極彩螺旋華", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Grok },
    { "Claude55", "サムネ映えする弾幕", "孔雀絢爛", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Claude },
    { "Qwen55", "サムネ映えする弾幕", "星喰うネオン蓮の絶頂", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Qwen },
    { "Kimi55", "サムネ映えする弾幕", "螺旋の花園", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Kimi },
    { "Zai55", "サムネ映えする弾幕", "彩華「極彩の万華鏡」", "Astral Blade Run", EnemyPat_ThumbnailFriendly_Zai },
    { "DeepSeek56", "エビングハウス錯視をモチーフにした弾幕", "錯視牢獄 - Ebbinghaus Cage -", "Locrian Barrage", EnemyPat_Ebbinghaus_DeepSeek },
    { "ChatGPT56", "エビングハウス錯視をモチーフにした弾幕", "エビングハウス・イリュージョン", "Locrian Barrage", EnemyPat_Ebbinghaus_ChatGPT },
    { "Gemini56", "エビングハウス錯視をモチーフにした弾幕", "錯視『相対的中心核』", "Locrian Barrage", EnemyPat_Ebbinghaus_Gemini },
    { "Grok56", "エビングハウス錯視をモチーフにした弾幕", "エビングハウス・イリュージョンリング", "Locrian Barrage", EnemyPat_Ebbinghaus_Grok },
    { "Claude56", "エビングハウス錯視をモチーフにした弾幕", "衆星拱月", "Locrian Barrage", EnemyPat_Ebbinghaus_Claude },
    { "Qwen56", "エビングハウス錯視をモチーフにした弾幕", "錯弾「エビングハウスの庭」", "Locrian Barrage", EnemyPat_Ebbinghaus_Qwen },
    { "Kimi56", "エビングハウス錯視をモチーフにした弾幕", "相対視の欺罔", "Locrian Barrage", EnemyPat_Ebbinghaus_Kimi },
    { "Zai56", "エビングハウス錯視をモチーフにした弾幕", "欺瞞の円環", "Locrian Barrage", EnemyPat_Ebbinghaus_Zai },
    { "DeepSeek57", "ルール30をモチーフにした弾幕", "ルール30の降下波動", "Bullet Hell Cascade", EnemyPat_Rule30_DeepSeek },
    { "ChatGPT57", "ルール30をモチーフにした弾幕", "ルール30・カオスフロント", "Bullet Hell Cascade", EnemyPat_Rule30_ChatGPT },
    { "Gemini57", "ルール30をモチーフにした弾幕", "カオスと秩序のセル・カスケード", "Bullet Hell Cascade", EnemyPat_Rule30_Gemini },
    { "Grok57", "ルール30をモチーフにした弾幕", "ルール30カスケード", "Bullet Hell Cascade", EnemyPat_Rule30_Grok },
    { "Claude57", "ルール30をモチーフにした弾幕", "一粒万倍", "Bullet Hell Cascade", EnemyPat_Rule30_Claude },
    { "Qwen57", "ルール30をモチーフにした弾幕", "ルール30：フラクタル・カスケード", "Bullet Hell Cascade", EnemyPat_Rule30_Qwen },
    { "Kimi57", "ルール30をモチーフにした弾幕", "非対称三角陣 ～Rule30～", "Bullet Hell Cascade", EnemyPat_Rule30_Kimi },
    { "Zai57", "ルール30をモチーフにした弾幕", "ルール30：非対称拡散弾幕", "Bullet Hell Cascade", EnemyPat_Rule30_Zai },
    { "DeepSeek58", "アリジゴクをモチーフにした弾幕", "底なし蟻地獄", "Desert Mirage Run", EnemyPat_Antlion_DeepSeek },
    { "ChatGPT58", "アリジゴクをモチーフにした弾幕", "蟻地獄", "Desert Mirage Run", EnemyPat_Antlion_ChatGPT },
    { "Gemini58", "アリジゴクをモチーフにした弾幕", "流砂の地獄陣（アントリオン・トラップ）", "Desert Mirage Run", EnemyPat_Antlion_Gemini },
    { "Grok58", "アリジゴクをモチーフにした弾幕", "砂坑の顎", "Desert Mirage Run", EnemyPat_Antlion_Grok },
    { "Claude58", "アリジゴクをモチーフにした弾幕", "蟻地獄陥穽", "Desert Mirage Run", EnemyPat_Antlion_Claude },
    { "Qwen58", "アリジゴクをモチーフにした弾幕", "砂漠の落とし穴 アントライオンの罠", "Desert Mirage Run", EnemyPat_Antlion_Qwen },
    { "Kimi58", "アリジゴクをモチーフにした弾幕", "漏斗陥穽（ろうとかんせい）－ Antlion Funnel", "Desert Mirage Run", EnemyPat_Antlion_Kimi },
    { "Zai58", "アリジゴクをモチーフにした弾幕", "帰路なき砂蟲の捕食円", "Desert Mirage Run", EnemyPat_Antlion_Zai },
    { "DeepSeek59", "三三七拍子のリズムで弾を撃つ弾幕", "祝砲乱舞「三三七拍子」", "Matsuri Bullet Run", EnemyPat_337Beat_DeepSeek },
    { "ChatGPT59", "三三七拍子のリズムで弾を撃つ弾幕", "三三七拍子連射", "Matsuri Bullet Run", EnemyPat_337Beat_ChatGPT },
    { "Gemini59", "三三七拍子のリズムで弾を撃つ弾幕", "祝砲・演舞三三七拍子", "Matsuri Bullet Run", EnemyPat_337Beat_Gemini },
    { "Grok59", "三三七拍子のリズムで弾を撃つ弾幕", "祝い撃ち", "Matsuri Bullet Run", EnemyPat_337Beat_Grok },
    { "Claude59", "三三七拍子のリズムで弾を撃つ弾幕", "三三七拍子 ―― 応援団風連続撃ち", "Matsuri Bullet Run", EnemyPat_337Beat_Claude },
    { "Qwen59", "三三七拍子のリズムで弾を撃つ弾幕", "神輿乱舞・三三七拍子", "Matsuri Bullet Run", EnemyPat_337Beat_Qwen },
    { "Kimi59", "三三七拍子のリズムで弾を撃つ弾幕", "三三七の舞（さんさんななのまい）", "Matsuri Bullet Run", EnemyPat_337Beat_Kimi },
    { "Zai59", "三三七拍子のリズムで弾を撃つ弾幕", "祭囃子・三三七の陣", "Matsuri Bullet Run", EnemyPat_337Beat_Zai },
    { "DeepSeek60", "ボスが撃ち返してくる弾幕", "散華の呪詛針（さんげのじゅそばり）", "Fractal Gamelan Rush", EnemyPat_Counter_DeepSeek },
    { "ChatGPT60", "ボスが撃ち返してくる弾幕", "報復の反響波", "Fractal Gamelan Rush", EnemyPat_Counter_ChatGPT },
    { "Gemini60", "ボスが撃ち返してくる弾幕", "波紋共鳴（リップル・カウンター）", "Fractal Gamelan Rush", EnemyPat_Counter_Gemini },
    { "Grok60", "ボスが撃ち返してくる弾幕", "傷の残響", "Fractal Gamelan Rush", EnemyPat_Counter_Grok },
    { "Claude60", "ボスが撃ち返してくる弾幕", "鏡面反撃「破鏡乱反射」", "Fractal Gamelan Rush", EnemyPat_Counter_Claude },
    { "Qwen60", "ボスが撃ち返してくる弾幕", "砕け散る紅硝子（クリムゾン・フラグメント）", "Fractal Gamelan Rush", EnemyPat_Counter_Qwen },
    { "Kimi60", "ボスが撃ち返してくる弾幕", "血の代償（Blood Tithe）", "Fractal Gamelan Rush", EnemyPat_Counter_Kimi },
    { "Zai60", "ボスが撃ち返してくる弾幕", "瞬停分裂弾", "Fractal Gamelan Rush", EnemyPat_Counter_Zai },
    { "DeepSeek61", "正十二面体をモチーフにした弾幕", "ドデカヘドラル・ケージ", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_DeepSeek },
    { "ChatGPT61", "正十二面体をモチーフにした弾幕", "十二面体結界", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_ChatGPT },
    { "Gemini61", "正十二面体をモチーフにした弾幕", "黄金正多面体陣 -Dodecahedron-", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Gemini },
    { "Grok61", "正十二面体をモチーフにした弾幕", "黄金立体の檻", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Grok },
    { "Claude61", "正十二面体をモチーフにした弾幕", "正十二面体・展開陣", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Claude },
    { "Qwen61", "正十二面体をモチーフにした弾幕", "幾何『正十二面体の鏡像』", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Qwen },
    { "Kimi61", "正十二面体をモチーフにした弾幕", "五重奏の十二審判", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Kimi },
    { "Zai61", "正十二面体をモチーフにした弾幕", "正十二面陣・虚数結界", "Crystalline Rain Circuit", EnemyPat_Dodecahedron_Zai },
    { "DeepSeek62", "カオスすぎる弾幕", "超次元崩壊輪廻（ハイパーカオス・サムサーラ）", "Bullet Hell Finale", EnemyPat_TooChaotic_DeepSeek },
    { "ChatGPT62", "カオスすぎる弾幕", "乱流回廊「スパイラル・スクランブル」", "Bullet Hell Finale", EnemyPat_TooChaotic_ChatGPT },
    { "Gemini62", "カオスすぎる弾幕", "確定性混沌（デターミニスティック・カオス）", "Bullet Hell Finale", EnemyPat_TooChaotic_Gemini },
    { "Grok62", "カオスすぎる弾幕", "虚数螺旋崩壊", "Bullet Hell Finale", EnemyPat_TooChaotic_Grok },
    { "Claude62", "カオスすぎる弾幕", "狂乱万華鏡", "Bullet Hell Finale", EnemyPat_TooChaotic_Claude },
    { "Qwen62", "カオスすぎる弾幕", "次元崩壊の万華鏡", "Bullet Hell Finale", EnemyPat_TooChaotic_Qwen },
    { "Kimi62", "カオスすぎる弾幕", "侵食多重螺旋「アポカリプティック・ネスト」", "Bullet Hell Finale", EnemyPat_TooChaotic_Kimi },
    { "Zai62", "カオスすぎる弾幕", "過負荷グリッチ・カスケード", "Bullet Hell Finale", EnemyPat_TooChaotic_Zai },
    { "DeepSeek63", "サインポールをモチーフにした弾幕", "バーバーズ・ポール", "Lochfire Arpeggio", EnemyPat_SignPole_DeepSeek },
    { "ChatGPT63", "サインポールをモチーフにした弾幕", "サインポール・スパイラル", "Lochfire Arpeggio", EnemyPat_SignPole_ChatGPT },
    { "Gemini63", "サインポールをモチーフにした弾幕", "トリコロール・ヘリックス", "Lochfire Arpeggio", EnemyPat_SignPole_Gemini },
    { "Grok63", "サインポールをモチーフにした弾幕", "サインポール螺旋", "Lochfire Arpeggio", EnemyPat_SignPole_Grok },
    { "Claude63", "サインポールをモチーフにした弾幕", "三色回転塔", "Lochfire Arpeggio", EnemyPat_SignPole_Claude },
    { "Qwen63", "サインポールをモチーフにした弾幕", "錯覚のサインポール・ラビリンス", "Lochfire Arpeggio", EnemyPat_SignPole_Qwen },
    { "Kimi63", "サインポールをモチーフにした弾幕", "交差点標識 － Crossroad Signpost", "Lochfire Arpeggio", EnemyPat_SignPole_Kimi },
    { "Zai63", "サインポールをモチーフにした弾幕", "カントリーサイン・フォール", "Lochfire Arpeggio", EnemyPat_SignPole_Zai },
    { "DeepSeek64", "三色団子をモチーフにした弾幕", "三色団子・串輪舞", "Moonlit Danmaku Run", EnemyPat_TricolorDango_DeepSeek },
    { "ChatGPT64", "三色団子をモチーフにした弾幕", "三色団子スパイラル", "Moonlit Danmaku Run", EnemyPat_TricolorDango_ChatGPT },
    { "Gemini64", "三色団子をモチーフにした弾幕", "春風・三色串崩し", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Gemini },
    { "Grok64", "三色団子をモチーフにした弾幕", "三色串刺し弾幕", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Grok },
    { "Claude64", "三色団子をモチーフにした弾幕", "三色串舞", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Claude },
    { "Qwen64", "三色団子をモチーフにした弾幕", "花見の宴・三色だんごの串刺し", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Qwen },
    { "Kimi64", "三色団子をモチーフにした弾幕", "花見団子の輪舞曲", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Kimi },
    { "Zai64", "三色団子をモチーフにした弾幕", "彩り三色・団子の逆転螺旋", "Moonlit Danmaku Run", EnemyPat_TricolorDango_Zai },
    { "DeepSeek65", "ヒュドラをモチーフにした弾幕", "不死結界「生首の庭」", "Nine Heads Rebirth", EnemyPat_Hydra_DeepSeek },
    { "ChatGPT65", "ヒュドラをモチーフにした弾幕", "", "Nine Heads Rebirth", EnemyPat_Hydra_ChatGPT },
    { "Gemini65", "ヒュドラをモチーフにした弾幕", "不滅の九頭連鎖（ハイドラ・リジェネシス）", "Nine Heads Rebirth", EnemyPat_Hydra_Gemini },
    { "Grok65", "ヒュドラをモチーフにした弾幕", "多頭再生弾幕", "Nine Heads Rebirth", EnemyPat_Hydra_Grok },
    { "Claude65", "ヒュドラをモチーフにした弾幕", "双首再生", "Nine Heads Rebirth", EnemyPat_Hydra_Claude },
    { "Qwen65", "ヒュドラをモチーフにした弾幕", "蛇再生「ヒュドラ・リジェネレイト」", "Nine Heads Rebirth", EnemyPat_Hydra_Qwen },
    { "Kimi65", "ヒュドラをモチーフにした弾幕", "断罪の輪廻 ― proliferating heads", "Nine Heads Rebirth", EnemyPat_Hydra_Kimi },
    { "Zai65", "ヒュドラをモチーフにした弾幕", "毒蛇の徘徊する吐息", "Nine Heads Rebirth", EnemyPat_Hydra_Zai },
    { "DeepSeek66", "超巨大弾を使った弾幕", "超巨大環状弾「縮檻 －シュクコウ－」", "Leviathan Shell", EnemyPat_HugeBullet_DeepSeek },
    { "ChatGPT66", "超巨大弾を使った弾幕", "重力核「グラビティ・コア」", "Leviathan Shell", EnemyPat_HugeBullet_ChatGPT },
    { "Gemini66", "超巨大弾を使った弾幕", "グラビティ・コアと破砕衝撃波", "Leviathan Shell", EnemyPat_HugeBullet_Gemini },
    { "Grok66", "超巨大弾を使った弾幕", "巨弾の呼吸・潮汐弾幕", "Leviathan Shell", EnemyPat_HugeBullet_Grok },
    { "Claude66", "超巨大弾を使った弾幕", "大玉転がし", "Leviathan Shell", EnemyPat_HugeBullet_Claude },
    { "Qwen66", "超巨大弾を使った弾幕", "超巨大弾「ムーンフォール・カーテン」", "Leviathan Shell", EnemyPat_HugeBullet_Qwen },
    { "Kimi66", "超巨大弾を使った弾幕", "重力の瞳（グラヴィティ・アイズ）", "Leviathan Shell", EnemyPat_HugeBullet_Kimi },
    { "Zai66", "超巨大弾を使った弾幕", "崩星の重核", "Leviathan Shell", EnemyPat_HugeBullet_Zai },
    { "DeepSeek67", "世界一難しい弾幕", "因果遡行『不可逆の残影』", "Cyber Doom Circuit", EnemyPat_TheHardest_DeepSeek },
    { "ChatGPT67", "世界一難しい弾幕", "カオス・イベントホライズン", "Cyber Doom Circuit", EnemyPat_TheHardest_ChatGPT },
    { "Gemini67", "世界一難しい弾幕", "量子位相干渉：事象の地平線", "Cyber Doom Circuit", EnemyPat_TheHardest_Gemini },
    { "Grok67", "世界一難しい弾幕", "無限螺旋・時間歪曲弾幕", "Cyber Doom Circuit", EnemyPat_TheHardest_Grok },
    { "Claude67", "世界一難しい弾幕", "終末刻鐘", "Cyber Doom Circuit", EnemyPat_TheHardest_Claude },
    { "Qwen67", "世界一難しい弾幕", "未来確定弾幕「ラプラスの最終定理」", "Cyber Doom Circuit", EnemyPat_TheHardest_Qwen },
    { "Kimi67", "世界一難しい弾幕", "無限分岐のカオス・フラクタル", "Cyber Doom Circuit", EnemyPat_TheHardest_Kimi },
    { "Zai67", "世界一難しい弾幕", "虚数迷宮・因果律の崩壊", "Cyber Doom Circuit", EnemyPat_TheHardest_Zai },
    { "DeepSeek68", "花火をモチーフにした弾幕", "大輪牡丹花火・千輪咲き", "Starburst Matsuri", EnemyPat_Firework_DeepSeek },
    { "ChatGPT68", "花火をモチーフにした弾幕", "残光花火", "Starburst Matsuri", EnemyPat_Firework_ChatGPT },
    { "Gemini68", "花火をモチーフにした弾幕", "昇り曲導付 尺玉千輪菊", "Starburst Matsuri", EnemyPat_Firework_Gemini },
    { "Grok68", "花火をモチーフにした弾幕", "菊花大輪", "Starburst Matsuri", EnemyPat_Firework_Grok },
    { "Claude68", "花火をモチーフにした弾幕", "尺玉二段咲き", "Starburst Matsuri", EnemyPat_Firework_Claude },
    { "Qwen68", "花火をモチーフにした弾幕", "花火「三尺玉・三段咲き」", "Starburst Matsuri", EnemyPat_Firework_Qwen },
    { "Kimi68", "花火をモチーフにした弾幕", "昇華の瞬間（アセンション・ブルーム）", "Starburst Matsuri", EnemyPat_Firework_Kimi },
    { "Zai68", "花火をモチーフにした弾幕", "二重咲き・昇華スターマイン", "Starburst Matsuri", EnemyPat_Firework_Zai },
    { "DeepSeek69", "スイカゲームをモチーフにした弾幕", "果実合成「弾けるスイカ連鎖」", "Watermelon Sky Run", EnemyPat_SuikaGame_DeepSeek },
    { "ChatGPT69", "スイカゲームをモチーフにした弾幕", "果実融合「スイカ連鎖フィーバー」", "Watermelon Sky Run", EnemyPat_SuikaGame_ChatGPT },
    { "Gemini69", "スイカゲームをモチーフにした弾幕", "シンカの連鎖弾（くだものフュージョン）", "Watermelon Sky Run", EnemyPat_SuikaGame_Gemini },
    { "Grok69", "スイカゲームをモチーフにした弾幕", "果実融合弾幕", "Watermelon Sky Run", EnemyPat_SuikaGame_Grok },
    { "Claude69", "スイカゲームをモチーフにした弾幕", "果実転生", "Watermelon Sky Run", EnemyPat_SuikaGame_Claude },
    { "Qwen69", "スイカゲームをモチーフにした弾幕", "果実合成のスイカ割り", "Watermelon Sky Run", EnemyPat_SuikaGame_Qwen },
    { "Kimi69", "スイカゲームをモチーフにした弾幕", "進化の果実列", "Watermelon Sky Run", EnemyPat_SuikaGame_Kimi },
    { "Zai69", "スイカゲームをモチーフにした弾幕", "重力合成弾幕・果実のカスケード", "Watermelon Sky Run", EnemyPat_SuikaGame_Zai },
    { "tmp", "お試し弾幕", "", "Torpedo_Hymn", EnemyPat_Tmp },
};