// stageData.cpp
#include "stageData.h"

std::vector<StageInfo> stageData = {
    // stageId, description, bgmFileName, patternFunc
    { "sample", "AIに渡すためのサンプル\n全種類の素材を使用", "field", EnemyPat_SampleForAI },
    { "handmade1", "3WAY自機狙い", "Torpedo_Hymn2", EnemyPat_3Way },
    { "handmade2", "全方位", "Torpedo_Hymn2", EnemyPat_Round },
    { "handmade3", "破裂弾", "Torpedo_Hymn2", EnemyPat_Burst },
    { "handmade4", "波と粒の境界（目コピ）", "Torpedo_Hymn2", EnemyPat_Namitsubu },
    { "deepseek", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_DeepSeek },
    { "gemini", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Gemini },
    { "chatgpt", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_ChatGPT },
    { "grok", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Grok },
    { "sakana", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Sakana },
    { "claude", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Claude },
    { "qwen", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Qwen },
    { "vibe", "幾何学的に美しい弾幕", "Chrome_Synapse", EnemyPat_Geometry_Vibe },
    { "deepseek2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_DeepSeek },
    { "gemini2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Gemini },
    { "chatgpt2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_ChatGPT },
    { "grok2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Grok },
    { "sakana2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Sakana },
    { "claude2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Claude },
    { "qwen2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Qwen },
    { "vibe2", "避けていて楽しい弾幕", "Polished_Thunder", EnemyPat_Dodge_Vibe },
    { "deepseek3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_DeepSeek },
    { "gemini3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Gemini },
    { "chatgpt3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_ChatGPT },
    { "grok3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Grok },
    { "sakana3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Sakana },
    { "claude3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Claude },
    { "qwen3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Qwen },
    { "vibe3", "見栄えのいい弾幕", "Chromed_Halo", EnemyPat_Beautiful_Vibe },
    { "deepseek4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_DeepSeek },
    { "gemini4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Gemini },
    { "chatgpt4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_ChatGPT },
    { "grok4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Grok },
    { "sakana4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Sakana },
    { "claude4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Claude },
    { "qwen4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Qwen },
    { "vibe4", "和風な弾幕", "Taiko_Lightning", EnemyPat_Japanese_Vibe },
    { "deepseek5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_DeepSeek },
    { "gemini5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Gemini },
    { "chatgpt5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_ChatGPT },
    { "grok5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Grok },
    { "sakana5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Sakana },
    { "claude5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Claude },
    { "qwen5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Qwen },
    { "vibe5", "滝をモチーフにした弾幕", "Taiko_Lightning2", EnemyPat_Waterfall_Vibe },
    { "deepseek6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_DeepSeek },
    { "gemini6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_Gemini },
    { "chatgpt6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_ChatGPT },
    { "grok6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_Grok },
    { "sakana6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_Sakana },
    { "claude6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_Claude },
    { "qwen6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namistubu_Qwen },
    { "vibe6", "波と粒の境界", "Clockwork_Rush", EnemyPat_Namitsubu_Vibe },
    { "deepseek7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_DeepSeek },
    { "chatgpt7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_ChatGPT },
    { "gemini7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Gemini },
    { "grok7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Grok },
    { "sakana7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Sakana },
    { "claude7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Claude },
    { "qwen7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Qwen },
    { "vibe7", "彗星をモチーフにした弾幕", "Nebula_Pulse_Loop", EnemyPat_Comet_Vibe },
    { "deepseek8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_DeepSeek },
    { "chatgpt8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_ChatGPT },
    { "gemini8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Gemini },
    { "grok8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Grok },
    { "sakana8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Sakana },
    { "claude8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Claude },
    { "qwen8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Qwen },
    { "vibe8", "雷をモチーフにした弾幕", "Clockwork_Rush2", EnemyPat_Thunder_Vibe },
    { "claudeEX1", "高難易度の弾幕", "Torpedo_Hymn", EnemyPat_Difficulty_Claude },
    { "claudeEX2", "幾何学的に美しい弾幕 アナザー", "Torpedo_Hymn", EnemyPat_Geometry_Claude2 },
    { "grokEX1", "彗星をモチーフにした弾幕 アナザー", "Torpedo_Hymn", EnemyPat_Comet_Grok2 },
    { "tmp", "tmp", "Torpedo_Hymn", EnemyPat_Tmp },
};